# config.yaml
gui:
  enabled: false

process:
  # type: "sequential"  # "sequential", "multi-thread", "multi-fiber"のいずれか
  concurrency: 1 #並行性
  parallelism: 1 #並列性

table:
  size: 1048576

cache:
  size: 1048576
