gui:
  enabled: false

process:
  parallel: true
  parallelism: 7

table:
  size: 16777216

cache:
  alive: true
  size: 1048576
  TLSSize: 823543

circuit:
  mode: "dynamic" # "sparse", "moderate", "dense", "dynamic"
  cancerMax: 1
  verbose: true
  timer: false

  Dealer:
    alive: false
    nonzeroWeight: 4.0
    controlBitWeight: 0.0
    targetBitWeight: 2.0
    shorteningWeight: 0.3
