gui:
  enabled: false

process:
  concurrency: 6 #並行性
  parallelism: 100 #並列性

table:
  size: 1048576

cache:
  alive: false
  size: 1048576

circuit:
  mode: "moderate" # "sparse", "moderate", "dense"
  cancerMax: 1
  verbose: false
  timer: false

  Dealer:
    alive: false
    nonzeroWeight: 4.0
    controlBitWeight: 0.0
    targetBitWeight: 2.0
    shorteningWeight: 0.3
