gui:
  enabled: false

process:
  parallel: true
  parallelism: 7

table:
  size: 1048576

cache:
  alive: true
  size: 1048576

circuit:
  mode: "moderate" # "sparse", "moderate", "dense"
  cancerMax: 1
  verbose: true
  timer: false

  Dealer:
    alive: true
    nonzeroWeight: 4.0
    controlBitWeight: 0.0
    targetBitWeight: 2.0
    shorteningWeight: 0.3
