OPENQASM 3.0;
include "stdgates.inc";
gate mcphase(_gate_p_0) _gate_q_0, _gate_q_1, _gate_q_2, _gate_q_3, _gate_q_4, _gate_q_5, _gate_q_6, _gate_q_7, _gate_q_8, _gate_q_9, _gate_q_10 {
  h _gate_q_10;
  cx _gate_q_7, _gate_q_10;
  tdg _gate_q_10;
  cx _gate_q_4, _gate_q_10;
  t _gate_q_10;
  cx _gate_q_7, _gate_q_10;
  tdg _gate_q_10;
  cx _gate_q_4, _gate_q_10;
  t _gate_q_7;
  t _gate_q_10;
  h _gate_q_10;
  cx _gate_q_4, _gate_q_7;
  t _gate_q_4;
  tdg _gate_q_7;
  cx _gate_q_4, _gate_q_7;
  h _gate_q_7;
  t _gate_q_7;
  cx _gate_q_3, _gate_q_7;
  tdg _gate_q_7;
  cx _gate_q_6, _gate_q_7;
  h _gate_q_6;
  t _gate_q_6;
  cx _gate_q_2, _gate_q_6;
  tdg _gate_q_6;
  cx _gate_q_5, _gate_q_6;
  h _gate_q_5;
  t _gate_q_5;
  cx _gate_q_1, _gate_q_5;
  tdg _gate_q_5;
  cx _gate_q_0, _gate_q_5;
  t _gate_q_5;
  cx _gate_q_1, _gate_q_5;
  tdg _gate_q_5;
  h _gate_q_5;
  cx _gate_q_5, _gate_q_6;
  t _gate_q_6;
  cx _gate_q_2, _gate_q_6;
  tdg _gate_q_6;
  h _gate_q_6;
  cx _gate_q_6, _gate_q_7;
  t _gate_q_7;
  cx _gate_q_3, _gate_q_7;
  tdg _gate_q_7;
  h _gate_q_7;
  h _gate_q_10;
  cx _gate_q_7, _gate_q_10;
  tdg _gate_q_10;
  cx _gate_q_4, _gate_q_10;
  t _gate_q_10;
  cx _gate_q_7, _gate_q_10;
  tdg _gate_q_10;
  cx _gate_q_4, _gate_q_10;
  t _gate_q_7;
  t _gate_q_10;
  h _gate_q_10;
  cx _gate_q_4, _gate_q_7;
  t _gate_q_4;
  tdg _gate_q_7;
  cx _gate_q_4, _gate_q_7;
  h _gate_q_7;
  t _gate_q_7;
  cx _gate_q_3, _gate_q_7;
  tdg _gate_q_7;
  cx _gate_q_6, _gate_q_7;
  h _gate_q_6;
  t _gate_q_6;
  cx _gate_q_2, _gate_q_6;
  tdg _gate_q_6;
  cx _gate_q_5, _gate_q_6;
  h _gate_q_5;
  t _gate_q_5;
  cx _gate_q_1, _gate_q_5;
  tdg _gate_q_5;
  cx _gate_q_0, _gate_q_5;
  t _gate_q_5;
  cx _gate_q_1, _gate_q_5;
  tdg _gate_q_5;
  h _gate_q_5;
  cx _gate_q_5, _gate_q_6;
  t _gate_q_6;
  cx _gate_q_2, _gate_q_6;
  tdg _gate_q_6;
  h _gate_q_6;
  cx _gate_q_6, _gate_q_7;
  t _gate_q_7;
  cx _gate_q_3, _gate_q_7;
  tdg _gate_q_7;
  h _gate_q_7;
  rz(-pi/4) _gate_q_10;
  h _gate_q_10;
  cx _gate_q_4, _gate_q_10;
  tdg _gate_q_10;
  cx _gate_q_9, _gate_q_10;
  t _gate_q_10;
  cx _gate_q_4, _gate_q_10;
  tdg _gate_q_10;
  cx _gate_q_9, _gate_q_10;
  t _gate_q_4;
  t _gate_q_10;
  h _gate_q_10;
  cx _gate_q_9, _gate_q_4;
  t _gate_q_9;
  tdg _gate_q_4;
  cx _gate_q_9, _gate_q_4;
  h _gate_q_4;
  t _gate_q_4;
  cx _gate_q_8, _gate_q_4;
  tdg _gate_q_4;
  cx _gate_q_3, _gate_q_4;
  h _gate_q_3;
  t _gate_q_3;
  cx _gate_q_7, _gate_q_3;
  tdg _gate_q_3;
  cx _gate_q_2, _gate_q_3;
  h _gate_q_2;
  t _gate_q_2;
  cx _gate_q_6, _gate_q_2;
  tdg _gate_q_2;
  cx _gate_q_5, _gate_q_2;
  t _gate_q_2;
  cx _gate_q_6, _gate_q_2;
  tdg _gate_q_2;
  h _gate_q_2;
  cx _gate_q_2, _gate_q_3;
  t _gate_q_3;
  cx _gate_q_7, _gate_q_3;
  tdg _gate_q_3;
  h _gate_q_3;
  cx _gate_q_3, _gate_q_4;
  t _gate_q_4;
  cx _gate_q_8, _gate_q_4;
  tdg _gate_q_4;
  h _gate_q_4;
  h _gate_q_10;
  cx _gate_q_4, _gate_q_10;
  tdg _gate_q_10;
  cx _gate_q_9, _gate_q_10;
  t _gate_q_10;
  cx _gate_q_4, _gate_q_10;
  tdg _gate_q_10;
  cx _gate_q_9, _gate_q_10;
  t _gate_q_4;
  t _gate_q_10;
  h _gate_q_10;
  cx _gate_q_9, _gate_q_4;
  t _gate_q_9;
  tdg _gate_q_4;
  cx _gate_q_9, _gate_q_4;
  h _gate_q_4;
  t _gate_q_4;
  cx _gate_q_8, _gate_q_4;
  tdg _gate_q_4;
  cx _gate_q_3, _gate_q_4;
  h _gate_q_3;
  t _gate_q_3;
  cx _gate_q_7, _gate_q_3;
  tdg _gate_q_3;
  cx _gate_q_2, _gate_q_3;
  h _gate_q_2;
  t _gate_q_2;
  cx _gate_q_6, _gate_q_2;
  tdg _gate_q_2;
  cx _gate_q_5, _gate_q_2;
  t _gate_q_2;
  cx _gate_q_6, _gate_q_2;
  tdg _gate_q_2;
  h _gate_q_2;
  cx _gate_q_2, _gate_q_3;
  t _gate_q_3;
  cx _gate_q_7, _gate_q_3;
  tdg _gate_q_3;
  h _gate_q_3;
  cx _gate_q_3, _gate_q_4;
  t _gate_q_4;
  cx _gate_q_8, _gate_q_4;
  tdg _gate_q_4;
  h _gate_q_4;
  rz(pi/4) _gate_q_10;
  h _gate_q_10;
  cx _gate_q_7, _gate_q_10;
  tdg _gate_q_10;
  cx _gate_q_4, _gate_q_10;
  t _gate_q_10;
  cx _gate_q_7, _gate_q_10;
  tdg _gate_q_10;
  cx _gate_q_4, _gate_q_10;
  t _gate_q_7;
  t _gate_q_10;
  h _gate_q_10;
  cx _gate_q_4, _gate_q_7;
  t _gate_q_4;
  tdg _gate_q_7;
  cx _gate_q_4, _gate_q_7;
  h _gate_q_7;
  t _gate_q_7;
  cx _gate_q_3, _gate_q_7;
  tdg _gate_q_7;
  cx _gate_q_6, _gate_q_7;
  h _gate_q_6;
  t _gate_q_6;
  cx _gate_q_2, _gate_q_6;
  tdg _gate_q_6;
  cx _gate_q_5, _gate_q_6;
  h _gate_q_5;
  t _gate_q_5;
  cx _gate_q_1, _gate_q_5;
  tdg _gate_q_5;
  cx _gate_q_0, _gate_q_5;
  t _gate_q_5;
  cx _gate_q_1, _gate_q_5;
  tdg _gate_q_5;
  h _gate_q_5;
  cx _gate_q_5, _gate_q_6;
  t _gate_q_6;
  cx _gate_q_2, _gate_q_6;
  tdg _gate_q_6;
  h _gate_q_6;
  cx _gate_q_6, _gate_q_7;
  t _gate_q_7;
  cx _gate_q_3, _gate_q_7;
  tdg _gate_q_7;
  h _gate_q_7;
  h _gate_q_10;
  cx _gate_q_7, _gate_q_10;
  tdg _gate_q_10;
  cx _gate_q_4, _gate_q_10;
  t _gate_q_10;
  cx _gate_q_7, _gate_q_10;
  tdg _gate_q_10;
  cx _gate_q_4, _gate_q_10;
  t _gate_q_7;
  t _gate_q_10;
  h _gate_q_10;
  cx _gate_q_4, _gate_q_7;
  t _gate_q_4;
  tdg _gate_q_7;
  cx _gate_q_4, _gate_q_7;
  h _gate_q_7;
  t _gate_q_7;
  cx _gate_q_3, _gate_q_7;
  tdg _gate_q_7;
  cx _gate_q_6, _gate_q_7;
  h _gate_q_6;
  t _gate_q_6;
  cx _gate_q_2, _gate_q_6;
  tdg _gate_q_6;
  cx _gate_q_5, _gate_q_6;
  h _gate_q_5;
  t _gate_q_5;
  cx _gate_q_1, _gate_q_5;
  tdg _gate_q_5;
  cx _gate_q_0, _gate_q_5;
  t _gate_q_5;
  cx _gate_q_1, _gate_q_5;
  tdg _gate_q_5;
  h _gate_q_5;
  cx _gate_q_5, _gate_q_6;
  t _gate_q_6;
  cx _gate_q_2, _gate_q_6;
  tdg _gate_q_6;
  h _gate_q_6;
  cx _gate_q_6, _gate_q_7;
  t _gate_q_7;
  cx _gate_q_3, _gate_q_7;
  tdg _gate_q_7;
  h _gate_q_7;
  rz(-pi/4) _gate_q_10;
  h _gate_q_10;
  cx _gate_q_4, _gate_q_10;
  tdg _gate_q_10;
  cx _gate_q_9, _gate_q_10;
  t _gate_q_10;
  cx _gate_q_4, _gate_q_10;
  tdg _gate_q_10;
  cx _gate_q_9, _gate_q_10;
  t _gate_q_4;
  t _gate_q_10;
  h _gate_q_10;
  cx _gate_q_9, _gate_q_4;
  t _gate_q_9;
  tdg _gate_q_4;
  cx _gate_q_9, _gate_q_4;
  h _gate_q_4;
  t _gate_q_4;
  cx _gate_q_8, _gate_q_4;
  tdg _gate_q_4;
  cx _gate_q_3, _gate_q_4;
  h _gate_q_3;
  t _gate_q_3;
  cx _gate_q_7, _gate_q_3;
  tdg _gate_q_3;
  cx _gate_q_2, _gate_q_3;
  h _gate_q_2;
  t _gate_q_2;
  cx _gate_q_6, _gate_q_2;
  tdg _gate_q_2;
  cx _gate_q_5, _gate_q_2;
  t _gate_q_2;
  cx _gate_q_6, _gate_q_2;
  tdg _gate_q_2;
  h _gate_q_2;
  cx _gate_q_2, _gate_q_3;
  t _gate_q_3;
  cx _gate_q_7, _gate_q_3;
  tdg _gate_q_3;
  h _gate_q_3;
  cx _gate_q_3, _gate_q_4;
  t _gate_q_4;
  cx _gate_q_8, _gate_q_4;
  tdg _gate_q_4;
  h _gate_q_4;
  h _gate_q_10;
  cx _gate_q_4, _gate_q_10;
  tdg _gate_q_10;
  cx _gate_q_9, _gate_q_10;
  t _gate_q_10;
  cx _gate_q_4, _gate_q_10;
  tdg _gate_q_10;
  cx _gate_q_9, _gate_q_10;
  t _gate_q_4;
  t _gate_q_10;
  h _gate_q_10;
  cx _gate_q_9, _gate_q_4;
  t _gate_q_9;
  tdg _gate_q_4;
  cx _gate_q_9, _gate_q_4;
  h _gate_q_4;
  t _gate_q_4;
  cx _gate_q_8, _gate_q_4;
  tdg _gate_q_4;
  cx _gate_q_3, _gate_q_4;
  h _gate_q_3;
  t _gate_q_3;
  cx _gate_q_7, _gate_q_3;
  tdg _gate_q_3;
  cx _gate_q_2, _gate_q_3;
  h _gate_q_2;
  t _gate_q_2;
  cx _gate_q_6, _gate_q_2;
  tdg _gate_q_2;
  cx _gate_q_5, _gate_q_2;
  t _gate_q_2;
  cx _gate_q_6, _gate_q_2;
  tdg _gate_q_2;
  h _gate_q_2;
  cx _gate_q_2, _gate_q_3;
  t _gate_q_3;
  cx _gate_q_7, _gate_q_3;
  tdg _gate_q_3;
  h _gate_q_3;
  cx _gate_q_3, _gate_q_4;
  t _gate_q_4;
  cx _gate_q_8, _gate_q_4;
  tdg _gate_q_4;
  h _gate_q_4;
  rz(pi/4) _gate_q_10;
  h _gate_q_9;
  cx _gate_q_7, _gate_q_9;
  tdg _gate_q_9;
  cx _gate_q_4, _gate_q_9;
  t _gate_q_9;
  cx _gate_q_7, _gate_q_9;
  tdg _gate_q_9;
  cx _gate_q_4, _gate_q_9;
  t _gate_q_7;
  t _gate_q_9;
  h _gate_q_9;
  cx _gate_q_4, _gate_q_7;
  t _gate_q_4;
  tdg _gate_q_7;
  cx _gate_q_4, _gate_q_7;
  h _gate_q_7;
  t _gate_q_7;
  cx _gate_q_3, _gate_q_7;
  tdg _gate_q_7;
  cx _gate_q_6, _gate_q_7;
  h _gate_q_6;
  t _gate_q_6;
  cx _gate_q_2, _gate_q_6;
  tdg _gate_q_6;
  cx _gate_q_5, _gate_q_6;
  h _gate_q_5;
  t _gate_q_5;
  cx _gate_q_1, _gate_q_5;
  tdg _gate_q_5;
  cx _gate_q_0, _gate_q_5;
  t _gate_q_5;
  cx _gate_q_1, _gate_q_5;
  tdg _gate_q_5;
  h _gate_q_5;
  cx _gate_q_5, _gate_q_6;
  t _gate_q_6;
  cx _gate_q_2, _gate_q_6;
  tdg _gate_q_6;
  h _gate_q_6;
  cx _gate_q_6, _gate_q_7;
  t _gate_q_7;
  cx _gate_q_3, _gate_q_7;
  tdg _gate_q_7;
  h _gate_q_7;
  h _gate_q_9;
  cx _gate_q_7, _gate_q_9;
  tdg _gate_q_9;
  cx _gate_q_4, _gate_q_9;
  t _gate_q_9;
  cx _gate_q_7, _gate_q_9;
  tdg _gate_q_9;
  cx _gate_q_4, _gate_q_9;
  t _gate_q_7;
  t _gate_q_9;
  h _gate_q_9;
  cx _gate_q_4, _gate_q_7;
  t _gate_q_4;
  tdg _gate_q_7;
  cx _gate_q_4, _gate_q_7;
  h _gate_q_7;
  t _gate_q_7;
  cx _gate_q_3, _gate_q_7;
  tdg _gate_q_7;
  cx _gate_q_6, _gate_q_7;
  h _gate_q_6;
  t _gate_q_6;
  cx _gate_q_2, _gate_q_6;
  tdg _gate_q_6;
  cx _gate_q_5, _gate_q_6;
  h _gate_q_5;
  t _gate_q_5;
  cx _gate_q_1, _gate_q_5;
  tdg _gate_q_5;
  cx _gate_q_0, _gate_q_5;
  t _gate_q_5;
  cx _gate_q_1, _gate_q_5;
  tdg _gate_q_5;
  h _gate_q_5;
  cx _gate_q_5, _gate_q_6;
  t _gate_q_6;
  cx _gate_q_2, _gate_q_6;
  tdg _gate_q_6;
  h _gate_q_6;
  cx _gate_q_6, _gate_q_7;
  t _gate_q_7;
  cx _gate_q_3, _gate_q_7;
  tdg _gate_q_7;
  h _gate_q_7;
  rz(-pi/8) _gate_q_9;
  h _gate_q_9;
  cx _gate_q_4, _gate_q_9;
  tdg _gate_q_9;
  cx _gate_q_8, _gate_q_9;
  t _gate_q_9;
  cx _gate_q_4, _gate_q_9;
  tdg _gate_q_9;
  cx _gate_q_8, _gate_q_9;
  t _gate_q_4;
  t _gate_q_9;
  h _gate_q_9;
  cx _gate_q_8, _gate_q_4;
  t _gate_q_8;
  tdg _gate_q_4;
  cx _gate_q_8, _gate_q_4;
  h _gate_q_4;
  t _gate_q_4;
  cx _gate_q_7, _gate_q_4;
  tdg _gate_q_4;
  cx _gate_q_3, _gate_q_4;
  h _gate_q_3;
  t _gate_q_3;
  cx _gate_q_6, _gate_q_3;
  tdg _gate_q_3;
  cx _gate_q_5, _gate_q_3;
  t _gate_q_3;
  cx _gate_q_6, _gate_q_3;
  tdg _gate_q_3;
  h _gate_q_3;
  cx _gate_q_3, _gate_q_4;
  t _gate_q_4;
  cx _gate_q_7, _gate_q_4;
  tdg _gate_q_4;
  h _gate_q_4;
  h _gate_q_9;
  cx _gate_q_4, _gate_q_9;
  tdg _gate_q_9;
  cx _gate_q_8, _gate_q_9;
  t _gate_q_9;
  cx _gate_q_4, _gate_q_9;
  tdg _gate_q_9;
  cx _gate_q_8, _gate_q_9;
  t _gate_q_4;
  t _gate_q_9;
  h _gate_q_9;
  cx _gate_q_8, _gate_q_4;
  t _gate_q_8;
  tdg _gate_q_4;
  cx _gate_q_8, _gate_q_4;
  h _gate_q_4;
  t _gate_q_4;
  cx _gate_q_7, _gate_q_4;
  tdg _gate_q_4;
  cx _gate_q_3, _gate_q_4;
  h _gate_q_3;
  t _gate_q_3;
  cx _gate_q_6, _gate_q_3;
  tdg _gate_q_3;
  cx _gate_q_5, _gate_q_3;
  t _gate_q_3;
  cx _gate_q_6, _gate_q_3;
  tdg _gate_q_3;
  h _gate_q_3;
  cx _gate_q_3, _gate_q_4;
  t _gate_q_4;
  cx _gate_q_7, _gate_q_4;
  tdg _gate_q_4;
  h _gate_q_4;
  rz(pi/8) _gate_q_9;
  h _gate_q_9;
  cx _gate_q_7, _gate_q_9;
  tdg _gate_q_9;
  cx _gate_q_4, _gate_q_9;
  t _gate_q_9;
  cx _gate_q_7, _gate_q_9;
  tdg _gate_q_9;
  cx _gate_q_4, _gate_q_9;
  t _gate_q_7;
  t _gate_q_9;
  h _gate_q_9;
  cx _gate_q_4, _gate_q_7;
  t _gate_q_4;
  tdg _gate_q_7;
  cx _gate_q_4, _gate_q_7;
  h _gate_q_7;
  t _gate_q_7;
  cx _gate_q_3, _gate_q_7;
  tdg _gate_q_7;
  cx _gate_q_6, _gate_q_7;
  h _gate_q_6;
  t _gate_q_6;
  cx _gate_q_2, _gate_q_6;
  tdg _gate_q_6;
  cx _gate_q_5, _gate_q_6;
  h _gate_q_5;
  t _gate_q_5;
  cx _gate_q_1, _gate_q_5;
  tdg _gate_q_5;
  cx _gate_q_0, _gate_q_5;
  t _gate_q_5;
  cx _gate_q_1, _gate_q_5;
  tdg _gate_q_5;
  h _gate_q_5;
  cx _gate_q_5, _gate_q_6;
  t _gate_q_6;
  cx _gate_q_2, _gate_q_6;
  tdg _gate_q_6;
  h _gate_q_6;
  cx _gate_q_6, _gate_q_7;
  t _gate_q_7;
  cx _gate_q_3, _gate_q_7;
  tdg _gate_q_7;
  h _gate_q_7;
  h _gate_q_9;
  cx _gate_q_7, _gate_q_9;
  tdg _gate_q_9;
  cx _gate_q_4, _gate_q_9;
  t _gate_q_9;
  cx _gate_q_7, _gate_q_9;
  tdg _gate_q_9;
  cx _gate_q_4, _gate_q_9;
  t _gate_q_7;
  t _gate_q_9;
  h _gate_q_9;
  cx _gate_q_4, _gate_q_7;
  t _gate_q_4;
  tdg _gate_q_7;
  cx _gate_q_4, _gate_q_7;
  h _gate_q_7;
  t _gate_q_7;
  cx _gate_q_3, _gate_q_7;
  tdg _gate_q_7;
  cx _gate_q_6, _gate_q_7;
  h _gate_q_6;
  t _gate_q_6;
  cx _gate_q_2, _gate_q_6;
  tdg _gate_q_6;
  cx _gate_q_5, _gate_q_6;
  h _gate_q_5;
  t _gate_q_5;
  cx _gate_q_1, _gate_q_5;
  tdg _gate_q_5;
  cx _gate_q_0, _gate_q_5;
  t _gate_q_5;
  cx _gate_q_1, _gate_q_5;
  tdg _gate_q_5;
  h _gate_q_5;
  cx _gate_q_5, _gate_q_6;
  t _gate_q_6;
  cx _gate_q_2, _gate_q_6;
  tdg _gate_q_6;
  h _gate_q_6;
  cx _gate_q_6, _gate_q_7;
  t _gate_q_7;
  cx _gate_q_3, _gate_q_7;
  tdg _gate_q_7;
  h _gate_q_7;
  rz(-pi/8) _gate_q_9;
  h _gate_q_9;
  cx _gate_q_4, _gate_q_9;
  tdg _gate_q_9;
  cx _gate_q_8, _gate_q_9;
  t _gate_q_9;
  cx _gate_q_4, _gate_q_9;
  tdg _gate_q_9;
  cx _gate_q_8, _gate_q_9;
  t _gate_q_4;
  t _gate_q_9;
  h _gate_q_9;
  cx _gate_q_8, _gate_q_4;
  t _gate_q_8;
  tdg _gate_q_4;
  cx _gate_q_8, _gate_q_4;
  h _gate_q_4;
  t _gate_q_4;
  cx _gate_q_7, _gate_q_4;
  tdg _gate_q_4;
  cx _gate_q_3, _gate_q_4;
  h _gate_q_3;
  t _gate_q_3;
  cx _gate_q_6, _gate_q_3;
  tdg _gate_q_3;
  cx _gate_q_5, _gate_q_3;
  t _gate_q_3;
  cx _gate_q_6, _gate_q_3;
  tdg _gate_q_3;
  h _gate_q_3;
  cx _gate_q_3, _gate_q_4;
  t _gate_q_4;
  cx _gate_q_7, _gate_q_4;
  tdg _gate_q_4;
  h _gate_q_4;
  h _gate_q_9;
  cx _gate_q_4, _gate_q_9;
  tdg _gate_q_9;
  cx _gate_q_8, _gate_q_9;
  t _gate_q_9;
  cx _gate_q_4, _gate_q_9;
  tdg _gate_q_9;
  cx _gate_q_8, _gate_q_9;
  t _gate_q_4;
  t _gate_q_9;
  h _gate_q_9;
  cx _gate_q_8, _gate_q_4;
  t _gate_q_8;
  tdg _gate_q_4;
  cx _gate_q_8, _gate_q_4;
  h _gate_q_4;
  t _gate_q_4;
  cx _gate_q_7, _gate_q_4;
  tdg _gate_q_4;
  cx _gate_q_3, _gate_q_4;
  h _gate_q_3;
  t _gate_q_3;
  cx _gate_q_6, _gate_q_3;
  tdg _gate_q_3;
  cx _gate_q_5, _gate_q_3;
  t _gate_q_3;
  cx _gate_q_6, _gate_q_3;
  tdg _gate_q_3;
  h _gate_q_3;
  cx _gate_q_3, _gate_q_4;
  t _gate_q_4;
  cx _gate_q_7, _gate_q_4;
  tdg _gate_q_4;
  h _gate_q_4;
  rz(pi/8) _gate_q_9;
  h _gate_q_8;
  cx _gate_q_5, _gate_q_8;
  tdg _gate_q_8;
  cx _gate_q_3, _gate_q_8;
  t _gate_q_8;
  cx _gate_q_5, _gate_q_8;
  tdg _gate_q_8;
  cx _gate_q_3, _gate_q_8;
  t _gate_q_5;
  t _gate_q_8;
  h _gate_q_8;
  cx _gate_q_3, _gate_q_5;
  t _gate_q_3;
  tdg _gate_q_5;
  cx _gate_q_3, _gate_q_5;
  h _gate_q_5;
  t _gate_q_5;
  cx _gate_q_2, _gate_q_5;
  tdg _gate_q_5;
  cx _gate_q_4, _gate_q_5;
  h _gate_q_4;
  t _gate_q_4;
  cx _gate_q_1, _gate_q_4;
  tdg _gate_q_4;
  cx _gate_q_0, _gate_q_4;
  t _gate_q_4;
  cx _gate_q_1, _gate_q_4;
  tdg _gate_q_4;
  h _gate_q_4;
  cx _gate_q_4, _gate_q_5;
  t _gate_q_5;
  cx _gate_q_2, _gate_q_5;
  tdg _gate_q_5;
  h _gate_q_5;
  h _gate_q_8;
  cx _gate_q_5, _gate_q_8;
  tdg _gate_q_8;
  cx _gate_q_3, _gate_q_8;
  t _gate_q_8;
  cx _gate_q_5, _gate_q_8;
  tdg _gate_q_8;
  cx _gate_q_3, _gate_q_8;
  t _gate_q_5;
  t _gate_q_8;
  h _gate_q_8;
  cx _gate_q_3, _gate_q_5;
  t _gate_q_3;
  tdg _gate_q_5;
  cx _gate_q_3, _gate_q_5;
  h _gate_q_5;
  t _gate_q_5;
  cx _gate_q_2, _gate_q_5;
  tdg _gate_q_5;
  cx _gate_q_4, _gate_q_5;
  h _gate_q_4;
  t _gate_q_4;
  cx _gate_q_1, _gate_q_4;
  tdg _gate_q_4;
  cx _gate_q_0, _gate_q_4;
  t _gate_q_4;
  cx _gate_q_1, _gate_q_4;
  tdg _gate_q_4;
  h _gate_q_4;
  cx _gate_q_4, _gate_q_5;
  t _gate_q_5;
  cx _gate_q_2, _gate_q_5;
  tdg _gate_q_5;
  h _gate_q_5;
  rz(-pi/16) _gate_q_8;
  h _gate_q_8;
  cx _gate_q_3, _gate_q_8;
  tdg _gate_q_8;
  cx _gate_q_7, _gate_q_8;
  t _gate_q_8;
  cx _gate_q_3, _gate_q_8;
  tdg _gate_q_8;
  cx _gate_q_7, _gate_q_8;
  t _gate_q_3;
  t _gate_q_8;
  h _gate_q_8;
  cx _gate_q_7, _gate_q_3;
  t _gate_q_7;
  tdg _gate_q_3;
  cx _gate_q_7, _gate_q_3;
  h _gate_q_3;
  t _gate_q_3;
  cx _gate_q_6, _gate_q_3;
  tdg _gate_q_3;
  cx _gate_q_2, _gate_q_3;
  h _gate_q_2;
  t _gate_q_2;
  cx _gate_q_5, _gate_q_2;
  tdg _gate_q_2;
  cx _gate_q_4, _gate_q_2;
  t _gate_q_2;
  cx _gate_q_5, _gate_q_2;
  tdg _gate_q_2;
  h _gate_q_2;
  cx _gate_q_2, _gate_q_3;
  t _gate_q_3;
  cx _gate_q_6, _gate_q_3;
  tdg _gate_q_3;
  h _gate_q_3;
  h _gate_q_8;
  cx _gate_q_3, _gate_q_8;
  tdg _gate_q_8;
  cx _gate_q_7, _gate_q_8;
  t _gate_q_8;
  cx _gate_q_3, _gate_q_8;
  tdg _gate_q_8;
  cx _gate_q_7, _gate_q_8;
  t _gate_q_3;
  t _gate_q_8;
  h _gate_q_8;
  cx _gate_q_7, _gate_q_3;
  t _gate_q_7;
  tdg _gate_q_3;
  cx _gate_q_7, _gate_q_3;
  h _gate_q_3;
  t _gate_q_3;
  cx _gate_q_6, _gate_q_3;
  tdg _gate_q_3;
  cx _gate_q_2, _gate_q_3;
  h _gate_q_2;
  t _gate_q_2;
  cx _gate_q_5, _gate_q_2;
  tdg _gate_q_2;
  cx _gate_q_4, _gate_q_2;
  t _gate_q_2;
  cx _gate_q_5, _gate_q_2;
  tdg _gate_q_2;
  h _gate_q_2;
  cx _gate_q_2, _gate_q_3;
  t _gate_q_3;
  cx _gate_q_6, _gate_q_3;
  tdg _gate_q_3;
  h _gate_q_3;
  rz(pi/16) _gate_q_8;
  h _gate_q_8;
  cx _gate_q_5, _gate_q_8;
  tdg _gate_q_8;
  cx _gate_q_3, _gate_q_8;
  t _gate_q_8;
  cx _gate_q_5, _gate_q_8;
  tdg _gate_q_8;
  cx _gate_q_3, _gate_q_8;
  t _gate_q_5;
  t _gate_q_8;
  h _gate_q_8;
  cx _gate_q_3, _gate_q_5;
  t _gate_q_3;
  tdg _gate_q_5;
  cx _gate_q_3, _gate_q_5;
  h _gate_q_5;
  t _gate_q_5;
  cx _gate_q_2, _gate_q_5;
  tdg _gate_q_5;
  cx _gate_q_4, _gate_q_5;
  h _gate_q_4;
  t _gate_q_4;
  cx _gate_q_1, _gate_q_4;
  tdg _gate_q_4;
  cx _gate_q_0, _gate_q_4;
  t _gate_q_4;
  cx _gate_q_1, _gate_q_4;
  tdg _gate_q_4;
  h _gate_q_4;
  cx _gate_q_4, _gate_q_5;
  t _gate_q_5;
  cx _gate_q_2, _gate_q_5;
  tdg _gate_q_5;
  h _gate_q_5;
  h _gate_q_8;
  cx _gate_q_5, _gate_q_8;
  tdg _gate_q_8;
  cx _gate_q_3, _gate_q_8;
  t _gate_q_8;
  cx _gate_q_5, _gate_q_8;
  tdg _gate_q_8;
  cx _gate_q_3, _gate_q_8;
  t _gate_q_5;
  t _gate_q_8;
  h _gate_q_8;
  cx _gate_q_3, _gate_q_5;
  t _gate_q_3;
  tdg _gate_q_5;
  cx _gate_q_3, _gate_q_5;
  h _gate_q_5;
  t _gate_q_5;
  cx _gate_q_2, _gate_q_5;
  tdg _gate_q_5;
  cx _gate_q_4, _gate_q_5;
  h _gate_q_4;
  t _gate_q_4;
  cx _gate_q_1, _gate_q_4;
  tdg _gate_q_4;
  cx _gate_q_0, _gate_q_4;
  t _gate_q_4;
  cx _gate_q_1, _gate_q_4;
  tdg _gate_q_4;
  h _gate_q_4;
  cx _gate_q_4, _gate_q_5;
  t _gate_q_5;
  cx _gate_q_2, _gate_q_5;
  tdg _gate_q_5;
  h _gate_q_5;
  rz(-pi/16) _gate_q_8;
  h _gate_q_8;
  cx _gate_q_3, _gate_q_8;
  tdg _gate_q_8;
  cx _gate_q_7, _gate_q_8;
  t _gate_q_8;
  cx _gate_q_3, _gate_q_8;
  tdg _gate_q_8;
  cx _gate_q_7, _gate_q_8;
  t _gate_q_3;
  t _gate_q_8;
  h _gate_q_8;
  cx _gate_q_7, _gate_q_3;
  t _gate_q_7;
  tdg _gate_q_3;
  cx _gate_q_7, _gate_q_3;
  h _gate_q_3;
  t _gate_q_3;
  cx _gate_q_6, _gate_q_3;
  tdg _gate_q_3;
  cx _gate_q_2, _gate_q_3;
  h _gate_q_2;
  t _gate_q_2;
  cx _gate_q_5, _gate_q_2;
  tdg _gate_q_2;
  cx _gate_q_4, _gate_q_2;
  t _gate_q_2;
  cx _gate_q_5, _gate_q_2;
  tdg _gate_q_2;
  h _gate_q_2;
  cx _gate_q_2, _gate_q_3;
  t _gate_q_3;
  cx _gate_q_6, _gate_q_3;
  tdg _gate_q_3;
  h _gate_q_3;
  h _gate_q_8;
  cx _gate_q_3, _gate_q_8;
  tdg _gate_q_8;
  cx _gate_q_7, _gate_q_8;
  t _gate_q_8;
  cx _gate_q_3, _gate_q_8;
  tdg _gate_q_8;
  cx _gate_q_7, _gate_q_8;
  t _gate_q_3;
  t _gate_q_8;
  h _gate_q_8;
  cx _gate_q_7, _gate_q_3;
  t _gate_q_7;
  tdg _gate_q_3;
  cx _gate_q_7, _gate_q_3;
  h _gate_q_3;
  t _gate_q_3;
  cx _gate_q_6, _gate_q_3;
  tdg _gate_q_3;
  cx _gate_q_2, _gate_q_3;
  h _gate_q_2;
  t _gate_q_2;
  cx _gate_q_5, _gate_q_2;
  tdg _gate_q_2;
  cx _gate_q_4, _gate_q_2;
  t _gate_q_2;
  cx _gate_q_5, _gate_q_2;
  tdg _gate_q_2;
  h _gate_q_2;
  cx _gate_q_2, _gate_q_3;
  t _gate_q_3;
  cx _gate_q_6, _gate_q_3;
  tdg _gate_q_3;
  h _gate_q_3;
  rz(pi/16) _gate_q_8;
  h _gate_q_7;
  cx _gate_q_5, _gate_q_7;
  tdg _gate_q_7;
  cx _gate_q_3, _gate_q_7;
  t _gate_q_7;
  cx _gate_q_5, _gate_q_7;
  tdg _gate_q_7;
  cx _gate_q_3, _gate_q_7;
  t _gate_q_5;
  t _gate_q_7;
  h _gate_q_7;
  cx _gate_q_3, _gate_q_5;
  t _gate_q_3;
  tdg _gate_q_5;
  cx _gate_q_3, _gate_q_5;
  h _gate_q_5;
  t _gate_q_5;
  cx _gate_q_2, _gate_q_5;
  tdg _gate_q_5;
  cx _gate_q_4, _gate_q_5;
  h _gate_q_4;
  t _gate_q_4;
  cx _gate_q_1, _gate_q_4;
  tdg _gate_q_4;
  cx _gate_q_0, _gate_q_4;
  t _gate_q_4;
  cx _gate_q_1, _gate_q_4;
  tdg _gate_q_4;
  h _gate_q_4;
  cx _gate_q_4, _gate_q_5;
  t _gate_q_5;
  cx _gate_q_2, _gate_q_5;
  tdg _gate_q_5;
  h _gate_q_5;
  h _gate_q_7;
  cx _gate_q_5, _gate_q_7;
  tdg _gate_q_7;
  cx _gate_q_3, _gate_q_7;
  t _gate_q_7;
  cx _gate_q_5, _gate_q_7;
  tdg _gate_q_7;
  cx _gate_q_3, _gate_q_7;
  t _gate_q_5;
  t _gate_q_7;
  h _gate_q_7;
  cx _gate_q_3, _gate_q_5;
  t _gate_q_3;
  tdg _gate_q_5;
  cx _gate_q_3, _gate_q_5;
  h _gate_q_5;
  t _gate_q_5;
  cx _gate_q_2, _gate_q_5;
  tdg _gate_q_5;
  cx _gate_q_4, _gate_q_5;
  h _gate_q_4;
  t _gate_q_4;
  cx _gate_q_1, _gate_q_4;
  tdg _gate_q_4;
  cx _gate_q_0, _gate_q_4;
  t _gate_q_4;
  cx _gate_q_1, _gate_q_4;
  tdg _gate_q_4;
  h _gate_q_4;
  cx _gate_q_4, _gate_q_5;
  t _gate_q_5;
  cx _gate_q_2, _gate_q_5;
  tdg _gate_q_5;
  h _gate_q_5;
  rz(-pi/32) _gate_q_7;
  h _gate_q_7;
  p(pi/8) _gate_q_4;
  p(pi/8) _gate_q_5;
  p(pi/8) _gate_q_6;
  p(pi/8) _gate_q_7;
  cx _gate_q_4, _gate_q_5;
  p(-pi/8) _gate_q_5;
  cx _gate_q_4, _gate_q_5;
  cx _gate_q_5, _gate_q_6;
  p(-pi/8) _gate_q_6;
  cx _gate_q_4, _gate_q_6;
  p(pi/8) _gate_q_6;
  cx _gate_q_5, _gate_q_6;
  p(-pi/8) _gate_q_6;
  cx _gate_q_4, _gate_q_6;
  cx _gate_q_6, _gate_q_7;
  p(-pi/8) _gate_q_7;
  cx _gate_q_5, _gate_q_7;
  p(pi/8) _gate_q_7;
  cx _gate_q_6, _gate_q_7;
  p(-pi/8) _gate_q_7;
  cx _gate_q_4, _gate_q_7;
  p(pi/8) _gate_q_7;
  cx _gate_q_6, _gate_q_7;
  p(-pi/8) _gate_q_7;
  cx _gate_q_5, _gate_q_7;
  p(pi/8) _gate_q_7;
  cx _gate_q_6, _gate_q_7;
  p(-pi/8) _gate_q_7;
  cx _gate_q_4, _gate_q_7;
  h _gate_q_7;
  rz(pi/32) _gate_q_7;
  h _gate_q_7;
  cx _gate_q_5, _gate_q_7;
  tdg _gate_q_7;
  cx _gate_q_3, _gate_q_7;
  t _gate_q_7;
  cx _gate_q_5, _gate_q_7;
  tdg _gate_q_7;
  cx _gate_q_3, _gate_q_7;
  t _gate_q_5;
  t _gate_q_7;
  h _gate_q_7;
  cx _gate_q_3, _gate_q_5;
  t _gate_q_3;
  tdg _gate_q_5;
  cx _gate_q_3, _gate_q_5;
  h _gate_q_5;
  t _gate_q_5;
  cx _gate_q_2, _gate_q_5;
  tdg _gate_q_5;
  cx _gate_q_4, _gate_q_5;
  h _gate_q_4;
  t _gate_q_4;
  cx _gate_q_1, _gate_q_4;
  tdg _gate_q_4;
  cx _gate_q_0, _gate_q_4;
  t _gate_q_4;
  cx _gate_q_1, _gate_q_4;
  tdg _gate_q_4;
  h _gate_q_4;
  cx _gate_q_4, _gate_q_5;
  t _gate_q_5;
  cx _gate_q_2, _gate_q_5;
  tdg _gate_q_5;
  h _gate_q_5;
  h _gate_q_7;
  cx _gate_q_5, _gate_q_7;
  tdg _gate_q_7;
  cx _gate_q_3, _gate_q_7;
  t _gate_q_7;
  cx _gate_q_5, _gate_q_7;
  tdg _gate_q_7;
  cx _gate_q_3, _gate_q_7;
  t _gate_q_5;
  t _gate_q_7;
  h _gate_q_7;
  cx _gate_q_3, _gate_q_5;
  t _gate_q_3;
  tdg _gate_q_5;
  cx _gate_q_3, _gate_q_5;
  h _gate_q_5;
  t _gate_q_5;
  cx _gate_q_2, _gate_q_5;
  tdg _gate_q_5;
  cx _gate_q_4, _gate_q_5;
  h _gate_q_4;
  t _gate_q_4;
  cx _gate_q_1, _gate_q_4;
  tdg _gate_q_4;
  cx _gate_q_0, _gate_q_4;
  t _gate_q_4;
  cx _gate_q_1, _gate_q_4;
  tdg _gate_q_4;
  h _gate_q_4;
  cx _gate_q_4, _gate_q_5;
  t _gate_q_5;
  cx _gate_q_2, _gate_q_5;
  tdg _gate_q_5;
  h _gate_q_5;
  rz(-pi/32) _gate_q_7;
  h _gate_q_7;
  p(pi/8) _gate_q_4;
  p(pi/8) _gate_q_5;
  p(pi/8) _gate_q_6;
  p(pi/8) _gate_q_7;
  cx _gate_q_4, _gate_q_5;
  p(-pi/8) _gate_q_5;
  cx _gate_q_4, _gate_q_5;
  cx _gate_q_5, _gate_q_6;
  p(-pi/8) _gate_q_6;
  cx _gate_q_4, _gate_q_6;
  p(pi/8) _gate_q_6;
  cx _gate_q_5, _gate_q_6;
  p(-pi/8) _gate_q_6;
  cx _gate_q_4, _gate_q_6;
  cx _gate_q_6, _gate_q_7;
  p(-pi/8) _gate_q_7;
  cx _gate_q_5, _gate_q_7;
  p(pi/8) _gate_q_7;
  cx _gate_q_6, _gate_q_7;
  p(-pi/8) _gate_q_7;
  cx _gate_q_4, _gate_q_7;
  p(pi/8) _gate_q_7;
  cx _gate_q_6, _gate_q_7;
  p(-pi/8) _gate_q_7;
  cx _gate_q_5, _gate_q_7;
  p(pi/8) _gate_q_7;
  cx _gate_q_6, _gate_q_7;
  p(-pi/8) _gate_q_7;
  cx _gate_q_4, _gate_q_7;
  h _gate_q_7;
  rz(pi/32) _gate_q_7;
  h _gate_q_6;
  p(pi/8) _gate_q_0;
  p(pi/8) _gate_q_1;
  p(pi/8) _gate_q_2;
  p(pi/8) _gate_q_6;
  cx _gate_q_0, _gate_q_1;
  p(-pi/8) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  cx _gate_q_1, _gate_q_2;
  p(-pi/8) _gate_q_2;
  cx _gate_q_0, _gate_q_2;
  p(pi/8) _gate_q_2;
  cx _gate_q_1, _gate_q_2;
  p(-pi/8) _gate_q_2;
  cx _gate_q_0, _gate_q_2;
  cx _gate_q_2, _gate_q_6;
  p(-pi/8) _gate_q_6;
  cx _gate_q_1, _gate_q_6;
  p(pi/8) _gate_q_6;
  cx _gate_q_2, _gate_q_6;
  p(-pi/8) _gate_q_6;
  cx _gate_q_0, _gate_q_6;
  p(pi/8) _gate_q_6;
  cx _gate_q_2, _gate_q_6;
  p(-pi/8) _gate_q_6;
  cx _gate_q_1, _gate_q_6;
  p(pi/8) _gate_q_6;
  cx _gate_q_2, _gate_q_6;
  p(-pi/8) _gate_q_6;
  cx _gate_q_0, _gate_q_6;
  h _gate_q_6;
  rz(-pi/64) _gate_q_6;
  h _gate_q_6;
  p(pi/8) _gate_q_3;
  p(pi/8) _gate_q_4;
  p(pi/8) _gate_q_5;
  p(pi/8) _gate_q_6;
  cx _gate_q_3, _gate_q_4;
  p(-pi/8) _gate_q_4;
  cx _gate_q_3, _gate_q_4;
  cx _gate_q_4, _gate_q_5;
  p(-pi/8) _gate_q_5;
  cx _gate_q_3, _gate_q_5;
  p(pi/8) _gate_q_5;
  cx _gate_q_4, _gate_q_5;
  p(-pi/8) _gate_q_5;
  cx _gate_q_3, _gate_q_5;
  cx _gate_q_5, _gate_q_6;
  p(-pi/8) _gate_q_6;
  cx _gate_q_4, _gate_q_6;
  p(pi/8) _gate_q_6;
  cx _gate_q_5, _gate_q_6;
  p(-pi/8) _gate_q_6;
  cx _gate_q_3, _gate_q_6;
  p(pi/8) _gate_q_6;
  cx _gate_q_5, _gate_q_6;
  p(-pi/8) _gate_q_6;
  cx _gate_q_4, _gate_q_6;
  p(pi/8) _gate_q_6;
  cx _gate_q_5, _gate_q_6;
  p(-pi/8) _gate_q_6;
  cx _gate_q_3, _gate_q_6;
  h _gate_q_6;
  rz(pi/64) _gate_q_6;
  h _gate_q_6;
  p(pi/8) _gate_q_0;
  p(pi/8) _gate_q_1;
  p(pi/8) _gate_q_2;
  p(pi/8) _gate_q_6;
  cx _gate_q_0, _gate_q_1;
  p(-pi/8) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  cx _gate_q_1, _gate_q_2;
  p(-pi/8) _gate_q_2;
  cx _gate_q_0, _gate_q_2;
  p(pi/8) _gate_q_2;
  cx _gate_q_1, _gate_q_2;
  p(-pi/8) _gate_q_2;
  cx _gate_q_0, _gate_q_2;
  cx _gate_q_2, _gate_q_6;
  p(-pi/8) _gate_q_6;
  cx _gate_q_1, _gate_q_6;
  p(pi/8) _gate_q_6;
  cx _gate_q_2, _gate_q_6;
  p(-pi/8) _gate_q_6;
  cx _gate_q_0, _gate_q_6;
  p(pi/8) _gate_q_6;
  cx _gate_q_2, _gate_q_6;
  p(-pi/8) _gate_q_6;
  cx _gate_q_1, _gate_q_6;
  p(pi/8) _gate_q_6;
  cx _gate_q_2, _gate_q_6;
  p(-pi/8) _gate_q_6;
  cx _gate_q_0, _gate_q_6;
  h _gate_q_6;
  rz(-pi/64) _gate_q_6;
  h _gate_q_6;
  p(pi/8) _gate_q_3;
  p(pi/8) _gate_q_4;
  p(pi/8) _gate_q_5;
  p(pi/8) _gate_q_6;
  cx _gate_q_3, _gate_q_4;
  p(-pi/8) _gate_q_4;
  cx _gate_q_3, _gate_q_4;
  cx _gate_q_4, _gate_q_5;
  p(-pi/8) _gate_q_5;
  cx _gate_q_3, _gate_q_5;
  p(pi/8) _gate_q_5;
  cx _gate_q_4, _gate_q_5;
  p(-pi/8) _gate_q_5;
  cx _gate_q_3, _gate_q_5;
  cx _gate_q_5, _gate_q_6;
  p(-pi/8) _gate_q_6;
  cx _gate_q_4, _gate_q_6;
  p(pi/8) _gate_q_6;
  cx _gate_q_5, _gate_q_6;
  p(-pi/8) _gate_q_6;
  cx _gate_q_3, _gate_q_6;
  p(pi/8) _gate_q_6;
  cx _gate_q_5, _gate_q_6;
  p(-pi/8) _gate_q_6;
  cx _gate_q_4, _gate_q_6;
  p(pi/8) _gate_q_6;
  cx _gate_q_5, _gate_q_6;
  p(-pi/8) _gate_q_6;
  cx _gate_q_3, _gate_q_6;
  h _gate_q_6;
  rz(pi/64) _gate_q_6;
  h _gate_q_5;
  p(pi/8) _gate_q_0;
  p(pi/8) _gate_q_1;
  p(pi/8) _gate_q_2;
  p(pi/8) _gate_q_5;
  cx _gate_q_0, _gate_q_1;
  p(-pi/8) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  cx _gate_q_1, _gate_q_2;
  p(-pi/8) _gate_q_2;
  cx _gate_q_0, _gate_q_2;
  p(pi/8) _gate_q_2;
  cx _gate_q_1, _gate_q_2;
  p(-pi/8) _gate_q_2;
  cx _gate_q_0, _gate_q_2;
  cx _gate_q_2, _gate_q_5;
  p(-pi/8) _gate_q_5;
  cx _gate_q_1, _gate_q_5;
  p(pi/8) _gate_q_5;
  cx _gate_q_2, _gate_q_5;
  p(-pi/8) _gate_q_5;
  cx _gate_q_0, _gate_q_5;
  p(pi/8) _gate_q_5;
  cx _gate_q_2, _gate_q_5;
  p(-pi/8) _gate_q_5;
  cx _gate_q_1, _gate_q_5;
  p(pi/8) _gate_q_5;
  cx _gate_q_2, _gate_q_5;
  p(-pi/8) _gate_q_5;
  cx _gate_q_0, _gate_q_5;
  h _gate_q_5;
  rz(-pi/128) _gate_q_5;
  h _gate_q_5;
  cx _gate_q_4, _gate_q_5;
  tdg _gate_q_5;
  cx _gate_q_3, _gate_q_5;
  t _gate_q_5;
  cx _gate_q_4, _gate_q_5;
  tdg _gate_q_5;
  cx _gate_q_3, _gate_q_5;
  t _gate_q_4;
  t _gate_q_5;
  h _gate_q_5;
  cx _gate_q_3, _gate_q_4;
  t _gate_q_3;
  tdg _gate_q_4;
  cx _gate_q_3, _gate_q_4;
  rz(pi/128) _gate_q_5;
  h _gate_q_5;
  p(pi/8) _gate_q_0;
  p(pi/8) _gate_q_1;
  p(pi/8) _gate_q_2;
  p(pi/8) _gate_q_5;
  cx _gate_q_0, _gate_q_1;
  p(-pi/8) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  cx _gate_q_1, _gate_q_2;
  p(-pi/8) _gate_q_2;
  cx _gate_q_0, _gate_q_2;
  p(pi/8) _gate_q_2;
  cx _gate_q_1, _gate_q_2;
  p(-pi/8) _gate_q_2;
  cx _gate_q_0, _gate_q_2;
  cx _gate_q_2, _gate_q_5;
  p(-pi/8) _gate_q_5;
  cx _gate_q_1, _gate_q_5;
  p(pi/8) _gate_q_5;
  cx _gate_q_2, _gate_q_5;
  p(-pi/8) _gate_q_5;
  cx _gate_q_0, _gate_q_5;
  p(pi/8) _gate_q_5;
  cx _gate_q_2, _gate_q_5;
  p(-pi/8) _gate_q_5;
  cx _gate_q_1, _gate_q_5;
  p(pi/8) _gate_q_5;
  cx _gate_q_2, _gate_q_5;
  p(-pi/8) _gate_q_5;
  cx _gate_q_0, _gate_q_5;
  h _gate_q_5;
  rz(-pi/128) _gate_q_5;
  h _gate_q_5;
  cx _gate_q_4, _gate_q_5;
  tdg _gate_q_5;
  cx _gate_q_3, _gate_q_5;
  t _gate_q_5;
  cx _gate_q_4, _gate_q_5;
  tdg _gate_q_5;
  cx _gate_q_3, _gate_q_5;
  t _gate_q_4;
  t _gate_q_5;
  h _gate_q_5;
  cx _gate_q_3, _gate_q_4;
  t _gate_q_3;
  tdg _gate_q_4;
  cx _gate_q_3, _gate_q_4;
  rz(pi/128) _gate_q_5;
  h _gate_q_4;
  cx _gate_q_1, _gate_q_4;
  tdg _gate_q_4;
  cx _gate_q_0, _gate_q_4;
  t _gate_q_4;
  cx _gate_q_1, _gate_q_4;
  tdg _gate_q_4;
  cx _gate_q_0, _gate_q_4;
  t _gate_q_1;
  t _gate_q_4;
  h _gate_q_4;
  cx _gate_q_0, _gate_q_1;
  t _gate_q_0;
  tdg _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  rz(-pi/256) _gate_q_4;
  h _gate_q_4;
  cx _gate_q_3, _gate_q_4;
  tdg _gate_q_4;
  cx _gate_q_2, _gate_q_4;
  t _gate_q_4;
  cx _gate_q_3, _gate_q_4;
  tdg _gate_q_4;
  cx _gate_q_2, _gate_q_4;
  t _gate_q_3;
  t _gate_q_4;
  h _gate_q_4;
  cx _gate_q_2, _gate_q_3;
  t _gate_q_2;
  tdg _gate_q_3;
  cx _gate_q_2, _gate_q_3;
  rz(pi/256) _gate_q_4;
  h _gate_q_4;
  cx _gate_q_1, _gate_q_4;
  tdg _gate_q_4;
  cx _gate_q_0, _gate_q_4;
  t _gate_q_4;
  cx _gate_q_1, _gate_q_4;
  tdg _gate_q_4;
  cx _gate_q_0, _gate_q_4;
  t _gate_q_1;
  t _gate_q_4;
  h _gate_q_4;
  cx _gate_q_0, _gate_q_1;
  t _gate_q_0;
  tdg _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  rz(-pi/256) _gate_q_4;
  h _gate_q_4;
  cx _gate_q_3, _gate_q_4;
  tdg _gate_q_4;
  cx _gate_q_2, _gate_q_4;
  t _gate_q_4;
  cx _gate_q_3, _gate_q_4;
  tdg _gate_q_4;
  cx _gate_q_2, _gate_q_4;
  t _gate_q_3;
  t _gate_q_4;
  h _gate_q_4;
  cx _gate_q_2, _gate_q_3;
  t _gate_q_2;
  tdg _gate_q_3;
  cx _gate_q_2, _gate_q_3;
  rz(pi/256) _gate_q_4;
  h _gate_q_3;
  cx _gate_q_1, _gate_q_3;
  tdg _gate_q_3;
  cx _gate_q_0, _gate_q_3;
  t _gate_q_3;
  cx _gate_q_1, _gate_q_3;
  tdg _gate_q_3;
  cx _gate_q_0, _gate_q_3;
  t _gate_q_1;
  t _gate_q_3;
  h _gate_q_3;
  cx _gate_q_0, _gate_q_1;
  t _gate_q_0;
  tdg _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  rz(-pi/512) _gate_q_3;
  cx _gate_q_2, _gate_q_3;
  rz(pi/512) _gate_q_3;
  h _gate_q_3;
  cx _gate_q_1, _gate_q_3;
  tdg _gate_q_3;
  cx _gate_q_0, _gate_q_3;
  t _gate_q_3;
  cx _gate_q_1, _gate_q_3;
  tdg _gate_q_3;
  cx _gate_q_0, _gate_q_3;
  t _gate_q_1;
  t _gate_q_3;
  h _gate_q_3;
  cx _gate_q_0, _gate_q_1;
  t _gate_q_0;
  tdg _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  rz(-pi/512) _gate_q_3;
  cx _gate_q_2, _gate_q_3;
  rz(pi/512) _gate_q_3;
  cx _gate_q_0, _gate_q_2;
  rz(-pi/1024) _gate_q_2;
  cx _gate_q_1, _gate_q_2;
  rz(pi/1024) _gate_q_2;
  cx _gate_q_0, _gate_q_2;
  rz(-pi/1024) _gate_q_2;
  cx _gate_q_1, _gate_q_2;
  rz(pi/1024) _gate_q_2;
  crz(pi/512) _gate_q_0, _gate_q_1;
  p(pi/1024) _gate_q_0;
}
gate mcphase_0(_gate_p_0) _gate_q_0, _gate_q_1, _gate_q_2, _gate_q_3, _gate_q_4, _gate_q_5, _gate_q_6, _gate_q_7, _gate_q_8, _gate_q_9 {
  h _gate_q_9;
  cx _gate_q_7, _gate_q_9;
  tdg _gate_q_9;
  cx _gate_q_4, _gate_q_9;
  t _gate_q_9;
  cx _gate_q_7, _gate_q_9;
  tdg _gate_q_9;
  cx _gate_q_4, _gate_q_9;
  t _gate_q_7;
  t _gate_q_9;
  h _gate_q_9;
  cx _gate_q_4, _gate_q_7;
  t _gate_q_4;
  tdg _gate_q_7;
  cx _gate_q_4, _gate_q_7;
  h _gate_q_7;
  t _gate_q_7;
  cx _gate_q_3, _gate_q_7;
  tdg _gate_q_7;
  cx _gate_q_6, _gate_q_7;
  h _gate_q_6;
  t _gate_q_6;
  cx _gate_q_2, _gate_q_6;
  tdg _gate_q_6;
  cx _gate_q_5, _gate_q_6;
  h _gate_q_5;
  t _gate_q_5;
  cx _gate_q_1, _gate_q_5;
  tdg _gate_q_5;
  cx _gate_q_0, _gate_q_5;
  t _gate_q_5;
  cx _gate_q_1, _gate_q_5;
  tdg _gate_q_5;
  h _gate_q_5;
  cx _gate_q_5, _gate_q_6;
  t _gate_q_6;
  cx _gate_q_2, _gate_q_6;
  tdg _gate_q_6;
  h _gate_q_6;
  cx _gate_q_6, _gate_q_7;
  t _gate_q_7;
  cx _gate_q_3, _gate_q_7;
  tdg _gate_q_7;
  h _gate_q_7;
  h _gate_q_9;
  cx _gate_q_7, _gate_q_9;
  tdg _gate_q_9;
  cx _gate_q_4, _gate_q_9;
  t _gate_q_9;
  cx _gate_q_7, _gate_q_9;
  tdg _gate_q_9;
  cx _gate_q_4, _gate_q_9;
  t _gate_q_7;
  t _gate_q_9;
  h _gate_q_9;
  cx _gate_q_4, _gate_q_7;
  t _gate_q_4;
  tdg _gate_q_7;
  cx _gate_q_4, _gate_q_7;
  h _gate_q_7;
  t _gate_q_7;
  cx _gate_q_3, _gate_q_7;
  tdg _gate_q_7;
  cx _gate_q_6, _gate_q_7;
  h _gate_q_6;
  t _gate_q_6;
  cx _gate_q_2, _gate_q_6;
  tdg _gate_q_6;
  cx _gate_q_5, _gate_q_6;
  h _gate_q_5;
  t _gate_q_5;
  cx _gate_q_1, _gate_q_5;
  tdg _gate_q_5;
  cx _gate_q_0, _gate_q_5;
  t _gate_q_5;
  cx _gate_q_1, _gate_q_5;
  tdg _gate_q_5;
  h _gate_q_5;
  cx _gate_q_5, _gate_q_6;
  t _gate_q_6;
  cx _gate_q_2, _gate_q_6;
  tdg _gate_q_6;
  h _gate_q_6;
  cx _gate_q_6, _gate_q_7;
  t _gate_q_7;
  cx _gate_q_3, _gate_q_7;
  tdg _gate_q_7;
  h _gate_q_7;
  rz(-pi/4) _gate_q_9;
  h _gate_q_9;
  cx _gate_q_4, _gate_q_9;
  tdg _gate_q_9;
  cx _gate_q_8, _gate_q_9;
  t _gate_q_9;
  cx _gate_q_4, _gate_q_9;
  tdg _gate_q_9;
  cx _gate_q_8, _gate_q_9;
  t _gate_q_4;
  t _gate_q_9;
  h _gate_q_9;
  cx _gate_q_8, _gate_q_4;
  t _gate_q_8;
  tdg _gate_q_4;
  cx _gate_q_8, _gate_q_4;
  h _gate_q_4;
  t _gate_q_4;
  cx _gate_q_7, _gate_q_4;
  tdg _gate_q_4;
  cx _gate_q_3, _gate_q_4;
  h _gate_q_3;
  t _gate_q_3;
  cx _gate_q_6, _gate_q_3;
  tdg _gate_q_3;
  cx _gate_q_5, _gate_q_3;
  t _gate_q_3;
  cx _gate_q_6, _gate_q_3;
  tdg _gate_q_3;
  h _gate_q_3;
  cx _gate_q_3, _gate_q_4;
  t _gate_q_4;
  cx _gate_q_7, _gate_q_4;
  tdg _gate_q_4;
  h _gate_q_4;
  h _gate_q_9;
  cx _gate_q_4, _gate_q_9;
  tdg _gate_q_9;
  cx _gate_q_8, _gate_q_9;
  t _gate_q_9;
  cx _gate_q_4, _gate_q_9;
  tdg _gate_q_9;
  cx _gate_q_8, _gate_q_9;
  t _gate_q_4;
  t _gate_q_9;
  h _gate_q_9;
  cx _gate_q_8, _gate_q_4;
  t _gate_q_8;
  tdg _gate_q_4;
  cx _gate_q_8, _gate_q_4;
  h _gate_q_4;
  t _gate_q_4;
  cx _gate_q_7, _gate_q_4;
  tdg _gate_q_4;
  cx _gate_q_3, _gate_q_4;
  h _gate_q_3;
  t _gate_q_3;
  cx _gate_q_6, _gate_q_3;
  tdg _gate_q_3;
  cx _gate_q_5, _gate_q_3;
  t _gate_q_3;
  cx _gate_q_6, _gate_q_3;
  tdg _gate_q_3;
  h _gate_q_3;
  cx _gate_q_3, _gate_q_4;
  t _gate_q_4;
  cx _gate_q_7, _gate_q_4;
  tdg _gate_q_4;
  h _gate_q_4;
  rz(pi/4) _gate_q_9;
  h _gate_q_9;
  cx _gate_q_7, _gate_q_9;
  tdg _gate_q_9;
  cx _gate_q_4, _gate_q_9;
  t _gate_q_9;
  cx _gate_q_7, _gate_q_9;
  tdg _gate_q_9;
  cx _gate_q_4, _gate_q_9;
  t _gate_q_7;
  t _gate_q_9;
  h _gate_q_9;
  cx _gate_q_4, _gate_q_7;
  t _gate_q_4;
  tdg _gate_q_7;
  cx _gate_q_4, _gate_q_7;
  h _gate_q_7;
  t _gate_q_7;
  cx _gate_q_3, _gate_q_7;
  tdg _gate_q_7;
  cx _gate_q_6, _gate_q_7;
  h _gate_q_6;
  t _gate_q_6;
  cx _gate_q_2, _gate_q_6;
  tdg _gate_q_6;
  cx _gate_q_5, _gate_q_6;
  h _gate_q_5;
  t _gate_q_5;
  cx _gate_q_1, _gate_q_5;
  tdg _gate_q_5;
  cx _gate_q_0, _gate_q_5;
  t _gate_q_5;
  cx _gate_q_1, _gate_q_5;
  tdg _gate_q_5;
  h _gate_q_5;
  cx _gate_q_5, _gate_q_6;
  t _gate_q_6;
  cx _gate_q_2, _gate_q_6;
  tdg _gate_q_6;
  h _gate_q_6;
  cx _gate_q_6, _gate_q_7;
  t _gate_q_7;
  cx _gate_q_3, _gate_q_7;
  tdg _gate_q_7;
  h _gate_q_7;
  h _gate_q_9;
  cx _gate_q_7, _gate_q_9;
  tdg _gate_q_9;
  cx _gate_q_4, _gate_q_9;
  t _gate_q_9;
  cx _gate_q_7, _gate_q_9;
  tdg _gate_q_9;
  cx _gate_q_4, _gate_q_9;
  t _gate_q_7;
  t _gate_q_9;
  h _gate_q_9;
  cx _gate_q_4, _gate_q_7;
  t _gate_q_4;
  tdg _gate_q_7;
  cx _gate_q_4, _gate_q_7;
  h _gate_q_7;
  t _gate_q_7;
  cx _gate_q_3, _gate_q_7;
  tdg _gate_q_7;
  cx _gate_q_6, _gate_q_7;
  h _gate_q_6;
  t _gate_q_6;
  cx _gate_q_2, _gate_q_6;
  tdg _gate_q_6;
  cx _gate_q_5, _gate_q_6;
  h _gate_q_5;
  t _gate_q_5;
  cx _gate_q_1, _gate_q_5;
  tdg _gate_q_5;
  cx _gate_q_0, _gate_q_5;
  t _gate_q_5;
  cx _gate_q_1, _gate_q_5;
  tdg _gate_q_5;
  h _gate_q_5;
  cx _gate_q_5, _gate_q_6;
  t _gate_q_6;
  cx _gate_q_2, _gate_q_6;
  tdg _gate_q_6;
  h _gate_q_6;
  cx _gate_q_6, _gate_q_7;
  t _gate_q_7;
  cx _gate_q_3, _gate_q_7;
  tdg _gate_q_7;
  h _gate_q_7;
  rz(-pi/4) _gate_q_9;
  h _gate_q_9;
  cx _gate_q_4, _gate_q_9;
  tdg _gate_q_9;
  cx _gate_q_8, _gate_q_9;
  t _gate_q_9;
  cx _gate_q_4, _gate_q_9;
  tdg _gate_q_9;
  cx _gate_q_8, _gate_q_9;
  t _gate_q_4;
  t _gate_q_9;
  h _gate_q_9;
  cx _gate_q_8, _gate_q_4;
  t _gate_q_8;
  tdg _gate_q_4;
  cx _gate_q_8, _gate_q_4;
  h _gate_q_4;
  t _gate_q_4;
  cx _gate_q_7, _gate_q_4;
  tdg _gate_q_4;
  cx _gate_q_3, _gate_q_4;
  h _gate_q_3;
  t _gate_q_3;
  cx _gate_q_6, _gate_q_3;
  tdg _gate_q_3;
  cx _gate_q_5, _gate_q_3;
  t _gate_q_3;
  cx _gate_q_6, _gate_q_3;
  tdg _gate_q_3;
  h _gate_q_3;
  cx _gate_q_3, _gate_q_4;
  t _gate_q_4;
  cx _gate_q_7, _gate_q_4;
  tdg _gate_q_4;
  h _gate_q_4;
  h _gate_q_9;
  cx _gate_q_4, _gate_q_9;
  tdg _gate_q_9;
  cx _gate_q_8, _gate_q_9;
  t _gate_q_9;
  cx _gate_q_4, _gate_q_9;
  tdg _gate_q_9;
  cx _gate_q_8, _gate_q_9;
  t _gate_q_4;
  t _gate_q_9;
  h _gate_q_9;
  cx _gate_q_8, _gate_q_4;
  t _gate_q_8;
  tdg _gate_q_4;
  cx _gate_q_8, _gate_q_4;
  h _gate_q_4;
  t _gate_q_4;
  cx _gate_q_7, _gate_q_4;
  tdg _gate_q_4;
  cx _gate_q_3, _gate_q_4;
  h _gate_q_3;
  t _gate_q_3;
  cx _gate_q_6, _gate_q_3;
  tdg _gate_q_3;
  cx _gate_q_5, _gate_q_3;
  t _gate_q_3;
  cx _gate_q_6, _gate_q_3;
  tdg _gate_q_3;
  h _gate_q_3;
  cx _gate_q_3, _gate_q_4;
  t _gate_q_4;
  cx _gate_q_7, _gate_q_4;
  tdg _gate_q_4;
  h _gate_q_4;
  rz(pi/4) _gate_q_9;
  h _gate_q_8;
  cx _gate_q_5, _gate_q_8;
  tdg _gate_q_8;
  cx _gate_q_3, _gate_q_8;
  t _gate_q_8;
  cx _gate_q_5, _gate_q_8;
  tdg _gate_q_8;
  cx _gate_q_3, _gate_q_8;
  t _gate_q_5;
  t _gate_q_8;
  h _gate_q_8;
  cx _gate_q_3, _gate_q_5;
  t _gate_q_3;
  tdg _gate_q_5;
  cx _gate_q_3, _gate_q_5;
  h _gate_q_5;
  t _gate_q_5;
  cx _gate_q_2, _gate_q_5;
  tdg _gate_q_5;
  cx _gate_q_4, _gate_q_5;
  h _gate_q_4;
  t _gate_q_4;
  cx _gate_q_1, _gate_q_4;
  tdg _gate_q_4;
  cx _gate_q_0, _gate_q_4;
  t _gate_q_4;
  cx _gate_q_1, _gate_q_4;
  tdg _gate_q_4;
  h _gate_q_4;
  cx _gate_q_4, _gate_q_5;
  t _gate_q_5;
  cx _gate_q_2, _gate_q_5;
  tdg _gate_q_5;
  h _gate_q_5;
  h _gate_q_8;
  cx _gate_q_5, _gate_q_8;
  tdg _gate_q_8;
  cx _gate_q_3, _gate_q_8;
  t _gate_q_8;
  cx _gate_q_5, _gate_q_8;
  tdg _gate_q_8;
  cx _gate_q_3, _gate_q_8;
  t _gate_q_5;
  t _gate_q_8;
  h _gate_q_8;
  cx _gate_q_3, _gate_q_5;
  t _gate_q_3;
  tdg _gate_q_5;
  cx _gate_q_3, _gate_q_5;
  h _gate_q_5;
  t _gate_q_5;
  cx _gate_q_2, _gate_q_5;
  tdg _gate_q_5;
  cx _gate_q_4, _gate_q_5;
  h _gate_q_4;
  t _gate_q_4;
  cx _gate_q_1, _gate_q_4;
  tdg _gate_q_4;
  cx _gate_q_0, _gate_q_4;
  t _gate_q_4;
  cx _gate_q_1, _gate_q_4;
  tdg _gate_q_4;
  h _gate_q_4;
  cx _gate_q_4, _gate_q_5;
  t _gate_q_5;
  cx _gate_q_2, _gate_q_5;
  tdg _gate_q_5;
  h _gate_q_5;
  rz(-pi/8) _gate_q_8;
  h _gate_q_8;
  cx _gate_q_3, _gate_q_8;
  tdg _gate_q_8;
  cx _gate_q_7, _gate_q_8;
  t _gate_q_8;
  cx _gate_q_3, _gate_q_8;
  tdg _gate_q_8;
  cx _gate_q_7, _gate_q_8;
  t _gate_q_3;
  t _gate_q_8;
  h _gate_q_8;
  cx _gate_q_7, _gate_q_3;
  t _gate_q_7;
  tdg _gate_q_3;
  cx _gate_q_7, _gate_q_3;
  h _gate_q_3;
  t _gate_q_3;
  cx _gate_q_6, _gate_q_3;
  tdg _gate_q_3;
  cx _gate_q_2, _gate_q_3;
  h _gate_q_2;
  t _gate_q_2;
  cx _gate_q_5, _gate_q_2;
  tdg _gate_q_2;
  cx _gate_q_4, _gate_q_2;
  t _gate_q_2;
  cx _gate_q_5, _gate_q_2;
  tdg _gate_q_2;
  h _gate_q_2;
  cx _gate_q_2, _gate_q_3;
  t _gate_q_3;
  cx _gate_q_6, _gate_q_3;
  tdg _gate_q_3;
  h _gate_q_3;
  h _gate_q_8;
  cx _gate_q_3, _gate_q_8;
  tdg _gate_q_8;
  cx _gate_q_7, _gate_q_8;
  t _gate_q_8;
  cx _gate_q_3, _gate_q_8;
  tdg _gate_q_8;
  cx _gate_q_7, _gate_q_8;
  t _gate_q_3;
  t _gate_q_8;
  h _gate_q_8;
  cx _gate_q_7, _gate_q_3;
  t _gate_q_7;
  tdg _gate_q_3;
  cx _gate_q_7, _gate_q_3;
  h _gate_q_3;
  t _gate_q_3;
  cx _gate_q_6, _gate_q_3;
  tdg _gate_q_3;
  cx _gate_q_2, _gate_q_3;
  h _gate_q_2;
  t _gate_q_2;
  cx _gate_q_5, _gate_q_2;
  tdg _gate_q_2;
  cx _gate_q_4, _gate_q_2;
  t _gate_q_2;
  cx _gate_q_5, _gate_q_2;
  tdg _gate_q_2;
  h _gate_q_2;
  cx _gate_q_2, _gate_q_3;
  t _gate_q_3;
  cx _gate_q_6, _gate_q_3;
  tdg _gate_q_3;
  h _gate_q_3;
  rz(pi/8) _gate_q_8;
  h _gate_q_8;
  cx _gate_q_5, _gate_q_8;
  tdg _gate_q_8;
  cx _gate_q_3, _gate_q_8;
  t _gate_q_8;
  cx _gate_q_5, _gate_q_8;
  tdg _gate_q_8;
  cx _gate_q_3, _gate_q_8;
  t _gate_q_5;
  t _gate_q_8;
  h _gate_q_8;
  cx _gate_q_3, _gate_q_5;
  t _gate_q_3;
  tdg _gate_q_5;
  cx _gate_q_3, _gate_q_5;
  h _gate_q_5;
  t _gate_q_5;
  cx _gate_q_2, _gate_q_5;
  tdg _gate_q_5;
  cx _gate_q_4, _gate_q_5;
  h _gate_q_4;
  t _gate_q_4;
  cx _gate_q_1, _gate_q_4;
  tdg _gate_q_4;
  cx _gate_q_0, _gate_q_4;
  t _gate_q_4;
  cx _gate_q_1, _gate_q_4;
  tdg _gate_q_4;
  h _gate_q_4;
  cx _gate_q_4, _gate_q_5;
  t _gate_q_5;
  cx _gate_q_2, _gate_q_5;
  tdg _gate_q_5;
  h _gate_q_5;
  h _gate_q_8;
  cx _gate_q_5, _gate_q_8;
  tdg _gate_q_8;
  cx _gate_q_3, _gate_q_8;
  t _gate_q_8;
  cx _gate_q_5, _gate_q_8;
  tdg _gate_q_8;
  cx _gate_q_3, _gate_q_8;
  t _gate_q_5;
  t _gate_q_8;
  h _gate_q_8;
  cx _gate_q_3, _gate_q_5;
  t _gate_q_3;
  tdg _gate_q_5;
  cx _gate_q_3, _gate_q_5;
  h _gate_q_5;
  t _gate_q_5;
  cx _gate_q_2, _gate_q_5;
  tdg _gate_q_5;
  cx _gate_q_4, _gate_q_5;
  h _gate_q_4;
  t _gate_q_4;
  cx _gate_q_1, _gate_q_4;
  tdg _gate_q_4;
  cx _gate_q_0, _gate_q_4;
  t _gate_q_4;
  cx _gate_q_1, _gate_q_4;
  tdg _gate_q_4;
  h _gate_q_4;
  cx _gate_q_4, _gate_q_5;
  t _gate_q_5;
  cx _gate_q_2, _gate_q_5;
  tdg _gate_q_5;
  h _gate_q_5;
  rz(-pi/8) _gate_q_8;
  h _gate_q_8;
  cx _gate_q_3, _gate_q_8;
  tdg _gate_q_8;
  cx _gate_q_7, _gate_q_8;
  t _gate_q_8;
  cx _gate_q_3, _gate_q_8;
  tdg _gate_q_8;
  cx _gate_q_7, _gate_q_8;
  t _gate_q_3;
  t _gate_q_8;
  h _gate_q_8;
  cx _gate_q_7, _gate_q_3;
  t _gate_q_7;
  tdg _gate_q_3;
  cx _gate_q_7, _gate_q_3;
  h _gate_q_3;
  t _gate_q_3;
  cx _gate_q_6, _gate_q_3;
  tdg _gate_q_3;
  cx _gate_q_2, _gate_q_3;
  h _gate_q_2;
  t _gate_q_2;
  cx _gate_q_5, _gate_q_2;
  tdg _gate_q_2;
  cx _gate_q_4, _gate_q_2;
  t _gate_q_2;
  cx _gate_q_5, _gate_q_2;
  tdg _gate_q_2;
  h _gate_q_2;
  cx _gate_q_2, _gate_q_3;
  t _gate_q_3;
  cx _gate_q_6, _gate_q_3;
  tdg _gate_q_3;
  h _gate_q_3;
  h _gate_q_8;
  cx _gate_q_3, _gate_q_8;
  tdg _gate_q_8;
  cx _gate_q_7, _gate_q_8;
  t _gate_q_8;
  cx _gate_q_3, _gate_q_8;
  tdg _gate_q_8;
  cx _gate_q_7, _gate_q_8;
  t _gate_q_3;
  t _gate_q_8;
  h _gate_q_8;
  cx _gate_q_7, _gate_q_3;
  t _gate_q_7;
  tdg _gate_q_3;
  cx _gate_q_7, _gate_q_3;
  h _gate_q_3;
  t _gate_q_3;
  cx _gate_q_6, _gate_q_3;
  tdg _gate_q_3;
  cx _gate_q_2, _gate_q_3;
  h _gate_q_2;
  t _gate_q_2;
  cx _gate_q_5, _gate_q_2;
  tdg _gate_q_2;
  cx _gate_q_4, _gate_q_2;
  t _gate_q_2;
  cx _gate_q_5, _gate_q_2;
  tdg _gate_q_2;
  h _gate_q_2;
  cx _gate_q_2, _gate_q_3;
  t _gate_q_3;
  cx _gate_q_6, _gate_q_3;
  tdg _gate_q_3;
  h _gate_q_3;
  rz(pi/8) _gate_q_8;
  h _gate_q_7;
  cx _gate_q_5, _gate_q_7;
  tdg _gate_q_7;
  cx _gate_q_3, _gate_q_7;
  t _gate_q_7;
  cx _gate_q_5, _gate_q_7;
  tdg _gate_q_7;
  cx _gate_q_3, _gate_q_7;
  t _gate_q_5;
  t _gate_q_7;
  h _gate_q_7;
  cx _gate_q_3, _gate_q_5;
  t _gate_q_3;
  tdg _gate_q_5;
  cx _gate_q_3, _gate_q_5;
  h _gate_q_5;
  t _gate_q_5;
  cx _gate_q_2, _gate_q_5;
  tdg _gate_q_5;
  cx _gate_q_4, _gate_q_5;
  h _gate_q_4;
  t _gate_q_4;
  cx _gate_q_1, _gate_q_4;
  tdg _gate_q_4;
  cx _gate_q_0, _gate_q_4;
  t _gate_q_4;
  cx _gate_q_1, _gate_q_4;
  tdg _gate_q_4;
  h _gate_q_4;
  cx _gate_q_4, _gate_q_5;
  t _gate_q_5;
  cx _gate_q_2, _gate_q_5;
  tdg _gate_q_5;
  h _gate_q_5;
  h _gate_q_7;
  cx _gate_q_5, _gate_q_7;
  tdg _gate_q_7;
  cx _gate_q_3, _gate_q_7;
  t _gate_q_7;
  cx _gate_q_5, _gate_q_7;
  tdg _gate_q_7;
  cx _gate_q_3, _gate_q_7;
  t _gate_q_5;
  t _gate_q_7;
  h _gate_q_7;
  cx _gate_q_3, _gate_q_5;
  t _gate_q_3;
  tdg _gate_q_5;
  cx _gate_q_3, _gate_q_5;
  h _gate_q_5;
  t _gate_q_5;
  cx _gate_q_2, _gate_q_5;
  tdg _gate_q_5;
  cx _gate_q_4, _gate_q_5;
  h _gate_q_4;
  t _gate_q_4;
  cx _gate_q_1, _gate_q_4;
  tdg _gate_q_4;
  cx _gate_q_0, _gate_q_4;
  t _gate_q_4;
  cx _gate_q_1, _gate_q_4;
  tdg _gate_q_4;
  h _gate_q_4;
  cx _gate_q_4, _gate_q_5;
  t _gate_q_5;
  cx _gate_q_2, _gate_q_5;
  tdg _gate_q_5;
  h _gate_q_5;
  rz(-pi/16) _gate_q_7;
  h _gate_q_7;
  p(pi/8) _gate_q_4;
  p(pi/8) _gate_q_5;
  p(pi/8) _gate_q_6;
  p(pi/8) _gate_q_7;
  cx _gate_q_4, _gate_q_5;
  p(-pi/8) _gate_q_5;
  cx _gate_q_4, _gate_q_5;
  cx _gate_q_5, _gate_q_6;
  p(-pi/8) _gate_q_6;
  cx _gate_q_4, _gate_q_6;
  p(pi/8) _gate_q_6;
  cx _gate_q_5, _gate_q_6;
  p(-pi/8) _gate_q_6;
  cx _gate_q_4, _gate_q_6;
  cx _gate_q_6, _gate_q_7;
  p(-pi/8) _gate_q_7;
  cx _gate_q_5, _gate_q_7;
  p(pi/8) _gate_q_7;
  cx _gate_q_6, _gate_q_7;
  p(-pi/8) _gate_q_7;
  cx _gate_q_4, _gate_q_7;
  p(pi/8) _gate_q_7;
  cx _gate_q_6, _gate_q_7;
  p(-pi/8) _gate_q_7;
  cx _gate_q_5, _gate_q_7;
  p(pi/8) _gate_q_7;
  cx _gate_q_6, _gate_q_7;
  p(-pi/8) _gate_q_7;
  cx _gate_q_4, _gate_q_7;
  h _gate_q_7;
  rz(pi/16) _gate_q_7;
  h _gate_q_7;
  cx _gate_q_5, _gate_q_7;
  tdg _gate_q_7;
  cx _gate_q_3, _gate_q_7;
  t _gate_q_7;
  cx _gate_q_5, _gate_q_7;
  tdg _gate_q_7;
  cx _gate_q_3, _gate_q_7;
  t _gate_q_5;
  t _gate_q_7;
  h _gate_q_7;
  cx _gate_q_3, _gate_q_5;
  t _gate_q_3;
  tdg _gate_q_5;
  cx _gate_q_3, _gate_q_5;
  h _gate_q_5;
  t _gate_q_5;
  cx _gate_q_2, _gate_q_5;
  tdg _gate_q_5;
  cx _gate_q_4, _gate_q_5;
  h _gate_q_4;
  t _gate_q_4;
  cx _gate_q_1, _gate_q_4;
  tdg _gate_q_4;
  cx _gate_q_0, _gate_q_4;
  t _gate_q_4;
  cx _gate_q_1, _gate_q_4;
  tdg _gate_q_4;
  h _gate_q_4;
  cx _gate_q_4, _gate_q_5;
  t _gate_q_5;
  cx _gate_q_2, _gate_q_5;
  tdg _gate_q_5;
  h _gate_q_5;
  h _gate_q_7;
  cx _gate_q_5, _gate_q_7;
  tdg _gate_q_7;
  cx _gate_q_3, _gate_q_7;
  t _gate_q_7;
  cx _gate_q_5, _gate_q_7;
  tdg _gate_q_7;
  cx _gate_q_3, _gate_q_7;
  t _gate_q_5;
  t _gate_q_7;
  h _gate_q_7;
  cx _gate_q_3, _gate_q_5;
  t _gate_q_3;
  tdg _gate_q_5;
  cx _gate_q_3, _gate_q_5;
  h _gate_q_5;
  t _gate_q_5;
  cx _gate_q_2, _gate_q_5;
  tdg _gate_q_5;
  cx _gate_q_4, _gate_q_5;
  h _gate_q_4;
  t _gate_q_4;
  cx _gate_q_1, _gate_q_4;
  tdg _gate_q_4;
  cx _gate_q_0, _gate_q_4;
  t _gate_q_4;
  cx _gate_q_1, _gate_q_4;
  tdg _gate_q_4;
  h _gate_q_4;
  cx _gate_q_4, _gate_q_5;
  t _gate_q_5;
  cx _gate_q_2, _gate_q_5;
  tdg _gate_q_5;
  h _gate_q_5;
  rz(-pi/16) _gate_q_7;
  h _gate_q_7;
  p(pi/8) _gate_q_4;
  p(pi/8) _gate_q_5;
  p(pi/8) _gate_q_6;
  p(pi/8) _gate_q_7;
  cx _gate_q_4, _gate_q_5;
  p(-pi/8) _gate_q_5;
  cx _gate_q_4, _gate_q_5;
  cx _gate_q_5, _gate_q_6;
  p(-pi/8) _gate_q_6;
  cx _gate_q_4, _gate_q_6;
  p(pi/8) _gate_q_6;
  cx _gate_q_5, _gate_q_6;
  p(-pi/8) _gate_q_6;
  cx _gate_q_4, _gate_q_6;
  cx _gate_q_6, _gate_q_7;
  p(-pi/8) _gate_q_7;
  cx _gate_q_5, _gate_q_7;
  p(pi/8) _gate_q_7;
  cx _gate_q_6, _gate_q_7;
  p(-pi/8) _gate_q_7;
  cx _gate_q_4, _gate_q_7;
  p(pi/8) _gate_q_7;
  cx _gate_q_6, _gate_q_7;
  p(-pi/8) _gate_q_7;
  cx _gate_q_5, _gate_q_7;
  p(pi/8) _gate_q_7;
  cx _gate_q_6, _gate_q_7;
  p(-pi/8) _gate_q_7;
  cx _gate_q_4, _gate_q_7;
  h _gate_q_7;
  rz(pi/16) _gate_q_7;
  h _gate_q_6;
  p(pi/8) _gate_q_0;
  p(pi/8) _gate_q_1;
  p(pi/8) _gate_q_2;
  p(pi/8) _gate_q_6;
  cx _gate_q_0, _gate_q_1;
  p(-pi/8) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  cx _gate_q_1, _gate_q_2;
  p(-pi/8) _gate_q_2;
  cx _gate_q_0, _gate_q_2;
  p(pi/8) _gate_q_2;
  cx _gate_q_1, _gate_q_2;
  p(-pi/8) _gate_q_2;
  cx _gate_q_0, _gate_q_2;
  cx _gate_q_2, _gate_q_6;
  p(-pi/8) _gate_q_6;
  cx _gate_q_1, _gate_q_6;
  p(pi/8) _gate_q_6;
  cx _gate_q_2, _gate_q_6;
  p(-pi/8) _gate_q_6;
  cx _gate_q_0, _gate_q_6;
  p(pi/8) _gate_q_6;
  cx _gate_q_2, _gate_q_6;
  p(-pi/8) _gate_q_6;
  cx _gate_q_1, _gate_q_6;
  p(pi/8) _gate_q_6;
  cx _gate_q_2, _gate_q_6;
  p(-pi/8) _gate_q_6;
  cx _gate_q_0, _gate_q_6;
  h _gate_q_6;
  rz(-pi/32) _gate_q_6;
  h _gate_q_6;
  p(pi/8) _gate_q_3;
  p(pi/8) _gate_q_4;
  p(pi/8) _gate_q_5;
  p(pi/8) _gate_q_6;
  cx _gate_q_3, _gate_q_4;
  p(-pi/8) _gate_q_4;
  cx _gate_q_3, _gate_q_4;
  cx _gate_q_4, _gate_q_5;
  p(-pi/8) _gate_q_5;
  cx _gate_q_3, _gate_q_5;
  p(pi/8) _gate_q_5;
  cx _gate_q_4, _gate_q_5;
  p(-pi/8) _gate_q_5;
  cx _gate_q_3, _gate_q_5;
  cx _gate_q_5, _gate_q_6;
  p(-pi/8) _gate_q_6;
  cx _gate_q_4, _gate_q_6;
  p(pi/8) _gate_q_6;
  cx _gate_q_5, _gate_q_6;
  p(-pi/8) _gate_q_6;
  cx _gate_q_3, _gate_q_6;
  p(pi/8) _gate_q_6;
  cx _gate_q_5, _gate_q_6;
  p(-pi/8) _gate_q_6;
  cx _gate_q_4, _gate_q_6;
  p(pi/8) _gate_q_6;
  cx _gate_q_5, _gate_q_6;
  p(-pi/8) _gate_q_6;
  cx _gate_q_3, _gate_q_6;
  h _gate_q_6;
  rz(pi/32) _gate_q_6;
  h _gate_q_6;
  p(pi/8) _gate_q_0;
  p(pi/8) _gate_q_1;
  p(pi/8) _gate_q_2;
  p(pi/8) _gate_q_6;
  cx _gate_q_0, _gate_q_1;
  p(-pi/8) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  cx _gate_q_1, _gate_q_2;
  p(-pi/8) _gate_q_2;
  cx _gate_q_0, _gate_q_2;
  p(pi/8) _gate_q_2;
  cx _gate_q_1, _gate_q_2;
  p(-pi/8) _gate_q_2;
  cx _gate_q_0, _gate_q_2;
  cx _gate_q_2, _gate_q_6;
  p(-pi/8) _gate_q_6;
  cx _gate_q_1, _gate_q_6;
  p(pi/8) _gate_q_6;
  cx _gate_q_2, _gate_q_6;
  p(-pi/8) _gate_q_6;
  cx _gate_q_0, _gate_q_6;
  p(pi/8) _gate_q_6;
  cx _gate_q_2, _gate_q_6;
  p(-pi/8) _gate_q_6;
  cx _gate_q_1, _gate_q_6;
  p(pi/8) _gate_q_6;
  cx _gate_q_2, _gate_q_6;
  p(-pi/8) _gate_q_6;
  cx _gate_q_0, _gate_q_6;
  h _gate_q_6;
  rz(-pi/32) _gate_q_6;
  h _gate_q_6;
  p(pi/8) _gate_q_3;
  p(pi/8) _gate_q_4;
  p(pi/8) _gate_q_5;
  p(pi/8) _gate_q_6;
  cx _gate_q_3, _gate_q_4;
  p(-pi/8) _gate_q_4;
  cx _gate_q_3, _gate_q_4;
  cx _gate_q_4, _gate_q_5;
  p(-pi/8) _gate_q_5;
  cx _gate_q_3, _gate_q_5;
  p(pi/8) _gate_q_5;
  cx _gate_q_4, _gate_q_5;
  p(-pi/8) _gate_q_5;
  cx _gate_q_3, _gate_q_5;
  cx _gate_q_5, _gate_q_6;
  p(-pi/8) _gate_q_6;
  cx _gate_q_4, _gate_q_6;
  p(pi/8) _gate_q_6;
  cx _gate_q_5, _gate_q_6;
  p(-pi/8) _gate_q_6;
  cx _gate_q_3, _gate_q_6;
  p(pi/8) _gate_q_6;
  cx _gate_q_5, _gate_q_6;
  p(-pi/8) _gate_q_6;
  cx _gate_q_4, _gate_q_6;
  p(pi/8) _gate_q_6;
  cx _gate_q_5, _gate_q_6;
  p(-pi/8) _gate_q_6;
  cx _gate_q_3, _gate_q_6;
  h _gate_q_6;
  rz(pi/32) _gate_q_6;
  h _gate_q_5;
  p(pi/8) _gate_q_0;
  p(pi/8) _gate_q_1;
  p(pi/8) _gate_q_2;
  p(pi/8) _gate_q_5;
  cx _gate_q_0, _gate_q_1;
  p(-pi/8) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  cx _gate_q_1, _gate_q_2;
  p(-pi/8) _gate_q_2;
  cx _gate_q_0, _gate_q_2;
  p(pi/8) _gate_q_2;
  cx _gate_q_1, _gate_q_2;
  p(-pi/8) _gate_q_2;
  cx _gate_q_0, _gate_q_2;
  cx _gate_q_2, _gate_q_5;
  p(-pi/8) _gate_q_5;
  cx _gate_q_1, _gate_q_5;
  p(pi/8) _gate_q_5;
  cx _gate_q_2, _gate_q_5;
  p(-pi/8) _gate_q_5;
  cx _gate_q_0, _gate_q_5;
  p(pi/8) _gate_q_5;
  cx _gate_q_2, _gate_q_5;
  p(-pi/8) _gate_q_5;
  cx _gate_q_1, _gate_q_5;
  p(pi/8) _gate_q_5;
  cx _gate_q_2, _gate_q_5;
  p(-pi/8) _gate_q_5;
  cx _gate_q_0, _gate_q_5;
  h _gate_q_5;
  rz(-pi/64) _gate_q_5;
  h _gate_q_5;
  cx _gate_q_4, _gate_q_5;
  tdg _gate_q_5;
  cx _gate_q_3, _gate_q_5;
  t _gate_q_5;
  cx _gate_q_4, _gate_q_5;
  tdg _gate_q_5;
  cx _gate_q_3, _gate_q_5;
  t _gate_q_4;
  t _gate_q_5;
  h _gate_q_5;
  cx _gate_q_3, _gate_q_4;
  t _gate_q_3;
  tdg _gate_q_4;
  cx _gate_q_3, _gate_q_4;
  rz(pi/64) _gate_q_5;
  h _gate_q_5;
  p(pi/8) _gate_q_0;
  p(pi/8) _gate_q_1;
  p(pi/8) _gate_q_2;
  p(pi/8) _gate_q_5;
  cx _gate_q_0, _gate_q_1;
  p(-pi/8) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  cx _gate_q_1, _gate_q_2;
  p(-pi/8) _gate_q_2;
  cx _gate_q_0, _gate_q_2;
  p(pi/8) _gate_q_2;
  cx _gate_q_1, _gate_q_2;
  p(-pi/8) _gate_q_2;
  cx _gate_q_0, _gate_q_2;
  cx _gate_q_2, _gate_q_5;
  p(-pi/8) _gate_q_5;
  cx _gate_q_1, _gate_q_5;
  p(pi/8) _gate_q_5;
  cx _gate_q_2, _gate_q_5;
  p(-pi/8) _gate_q_5;
  cx _gate_q_0, _gate_q_5;
  p(pi/8) _gate_q_5;
  cx _gate_q_2, _gate_q_5;
  p(-pi/8) _gate_q_5;
  cx _gate_q_1, _gate_q_5;
  p(pi/8) _gate_q_5;
  cx _gate_q_2, _gate_q_5;
  p(-pi/8) _gate_q_5;
  cx _gate_q_0, _gate_q_5;
  h _gate_q_5;
  rz(-pi/64) _gate_q_5;
  h _gate_q_5;
  cx _gate_q_4, _gate_q_5;
  tdg _gate_q_5;
  cx _gate_q_3, _gate_q_5;
  t _gate_q_5;
  cx _gate_q_4, _gate_q_5;
  tdg _gate_q_5;
  cx _gate_q_3, _gate_q_5;
  t _gate_q_4;
  t _gate_q_5;
  h _gate_q_5;
  cx _gate_q_3, _gate_q_4;
  t _gate_q_3;
  tdg _gate_q_4;
  cx _gate_q_3, _gate_q_4;
  rz(pi/64) _gate_q_5;
  h _gate_q_4;
  cx _gate_q_1, _gate_q_4;
  tdg _gate_q_4;
  cx _gate_q_0, _gate_q_4;
  t _gate_q_4;
  cx _gate_q_1, _gate_q_4;
  tdg _gate_q_4;
  cx _gate_q_0, _gate_q_4;
  t _gate_q_1;
  t _gate_q_4;
  h _gate_q_4;
  cx _gate_q_0, _gate_q_1;
  t _gate_q_0;
  tdg _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  rz(-pi/128) _gate_q_4;
  h _gate_q_4;
  cx _gate_q_3, _gate_q_4;
  tdg _gate_q_4;
  cx _gate_q_2, _gate_q_4;
  t _gate_q_4;
  cx _gate_q_3, _gate_q_4;
  tdg _gate_q_4;
  cx _gate_q_2, _gate_q_4;
  t _gate_q_3;
  t _gate_q_4;
  h _gate_q_4;
  cx _gate_q_2, _gate_q_3;
  t _gate_q_2;
  tdg _gate_q_3;
  cx _gate_q_2, _gate_q_3;
  rz(pi/128) _gate_q_4;
  h _gate_q_4;
  cx _gate_q_1, _gate_q_4;
  tdg _gate_q_4;
  cx _gate_q_0, _gate_q_4;
  t _gate_q_4;
  cx _gate_q_1, _gate_q_4;
  tdg _gate_q_4;
  cx _gate_q_0, _gate_q_4;
  t _gate_q_1;
  t _gate_q_4;
  h _gate_q_4;
  cx _gate_q_0, _gate_q_1;
  t _gate_q_0;
  tdg _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  rz(-pi/128) _gate_q_4;
  h _gate_q_4;
  cx _gate_q_3, _gate_q_4;
  tdg _gate_q_4;
  cx _gate_q_2, _gate_q_4;
  t _gate_q_4;
  cx _gate_q_3, _gate_q_4;
  tdg _gate_q_4;
  cx _gate_q_2, _gate_q_4;
  t _gate_q_3;
  t _gate_q_4;
  h _gate_q_4;
  cx _gate_q_2, _gate_q_3;
  t _gate_q_2;
  tdg _gate_q_3;
  cx _gate_q_2, _gate_q_3;
  rz(pi/128) _gate_q_4;
  h _gate_q_3;
  cx _gate_q_1, _gate_q_3;
  tdg _gate_q_3;
  cx _gate_q_0, _gate_q_3;
  t _gate_q_3;
  cx _gate_q_1, _gate_q_3;
  tdg _gate_q_3;
  cx _gate_q_0, _gate_q_3;
  t _gate_q_1;
  t _gate_q_3;
  h _gate_q_3;
  cx _gate_q_0, _gate_q_1;
  t _gate_q_0;
  tdg _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  rz(-pi/256) _gate_q_3;
  cx _gate_q_2, _gate_q_3;
  rz(pi/256) _gate_q_3;
  h _gate_q_3;
  cx _gate_q_1, _gate_q_3;
  tdg _gate_q_3;
  cx _gate_q_0, _gate_q_3;
  t _gate_q_3;
  cx _gate_q_1, _gate_q_3;
  tdg _gate_q_3;
  cx _gate_q_0, _gate_q_3;
  t _gate_q_1;
  t _gate_q_3;
  h _gate_q_3;
  cx _gate_q_0, _gate_q_1;
  t _gate_q_0;
  tdg _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  rz(-pi/256) _gate_q_3;
  cx _gate_q_2, _gate_q_3;
  rz(pi/256) _gate_q_3;
  cx _gate_q_0, _gate_q_2;
  rz(-pi/512) _gate_q_2;
  cx _gate_q_1, _gate_q_2;
  rz(pi/512) _gate_q_2;
  cx _gate_q_0, _gate_q_2;
  rz(-pi/512) _gate_q_2;
  cx _gate_q_1, _gate_q_2;
  rz(pi/512) _gate_q_2;
  crz(pi/256) _gate_q_0, _gate_q_1;
  p(pi/512) _gate_q_0;
}
gate mcx _gate_q_0, _gate_q_1, _gate_q_2, _gate_q_3, _gate_q_4, _gate_q_5, _gate_q_6, _gate_q_7, _gate_q_8, _gate_q_9 {
  h _gate_q_9;
  mcphase_0 _gate_q_0, _gate_q_1, _gate_q_2, _gate_q_3, _gate_q_4, _gate_q_5, _gate_q_6, _gate_q_7, _gate_q_8, _gate_q_9;
  h _gate_q_9;
}
gate Q _gate_q_0, _gate_q_1, _gate_q_2, _gate_q_3, _gate_q_4, _gate_q_5, _gate_q_6, _gate_q_7, _gate_q_8, _gate_q_9, _gate_q_10 {
  mcphase(pi) _gate_q_0, _gate_q_1, _gate_q_2, _gate_q_3, _gate_q_4, _gate_q_5, _gate_q_6, _gate_q_7, _gate_q_8, _gate_q_9, _gate_q_10;
  h _gate_q_0;
  h _gate_q_1;
  h _gate_q_2;
  h _gate_q_3;
  h _gate_q_4;
  h _gate_q_5;
  h _gate_q_6;
  h _gate_q_7;
  h _gate_q_8;
  h _gate_q_9;
  x _gate_q_0;
  x _gate_q_1;
  x _gate_q_2;
  x _gate_q_3;
  x _gate_q_4;
  x _gate_q_5;
  x _gate_q_6;
  x _gate_q_7;
  x _gate_q_8;
  x _gate_q_9;
  h _gate_q_9;
  mcx _gate_q_0, _gate_q_1, _gate_q_2, _gate_q_3, _gate_q_4, _gate_q_5, _gate_q_6, _gate_q_7, _gate_q_8, _gate_q_9;
  h _gate_q_9;
  x _gate_q_0;
  x _gate_q_1;
  x _gate_q_2;
  x _gate_q_3;
  x _gate_q_4;
  x _gate_q_5;
  x _gate_q_6;
  x _gate_q_7;
  x _gate_q_8;
  x _gate_q_9;
  h _gate_q_0;
  h _gate_q_1;
  h _gate_q_2;
  h _gate_q_3;
  h _gate_q_4;
  h _gate_q_5;
  h _gate_q_6;
  h _gate_q_7;
  h _gate_q_8;
  h _gate_q_9;
}
bit[11] meas;
qubit[10] q;
qubit[1] flag;
h q[0];
h q[1];
h q[2];
h q[3];
h q[4];
h q[5];
h q[6];
h q[7];
h q[8];
h q[9];
x flag[0];
Q q[0], q[1], q[2], q[3], q[4], q[5], q[6], q[7], q[8], q[9], flag[0];
Q q[0], q[1], q[2], q[3], q[4], q[5], q[6], q[7], q[8], q[9], flag[0];
Q q[0], q[1], q[2], q[3], q[4], q[5], q[6], q[7], q[8], q[9], flag[0];
Q q[0], q[1], q[2], q[3], q[4], q[5], q[6], q[7], q[8], q[9], flag[0];
Q q[0], q[1], q[2], q[3], q[4], q[5], q[6], q[7], q[8], q[9], flag[0];
Q q[0], q[1], q[2], q[3], q[4], q[5], q[6], q[7], q[8], q[9], flag[0];
Q q[0], q[1], q[2], q[3], q[4], q[5], q[6], q[7], q[8], q[9], flag[0];
Q q[0], q[1], q[2], q[3], q[4], q[5], q[6], q[7], q[8], q[9], flag[0];
Q q[0], q[1], q[2], q[3], q[4], q[5], q[6], q[7], q[8], q[9], flag[0];
Q q[0], q[1], q[2], q[3], q[4], q[5], q[6], q[7], q[8], q[9], flag[0];
Q q[0], q[1], q[2], q[3], q[4], q[5], q[6], q[7], q[8], q[9], flag[0];
Q q[0], q[1], q[2], q[3], q[4], q[5], q[6], q[7], q[8], q[9], flag[0];
Q q[0], q[1], q[2], q[3], q[4], q[5], q[6], q[7], q[8], q[9], flag[0];
Q q[0], q[1], q[2], q[3], q[4], q[5], q[6], q[7], q[8], q[9], flag[0];
Q q[0], q[1], q[2], q[3], q[4], q[5], q[6], q[7], q[8], q[9], flag[0];
Q q[0], q[1], q[2], q[3], q[4], q[5], q[6], q[7], q[8], q[9], flag[0];
Q q[0], q[1], q[2], q[3], q[4], q[5], q[6], q[7], q[8], q[9], flag[0];
Q q[0], q[1], q[2], q[3], q[4], q[5], q[6], q[7], q[8], q[9], flag[0];
Q q[0], q[1], q[2], q[3], q[4], q[5], q[6], q[7], q[8], q[9], flag[0];
Q q[0], q[1], q[2], q[3], q[4], q[5], q[6], q[7], q[8], q[9], flag[0];
Q q[0], q[1], q[2], q[3], q[4], q[5], q[6], q[7], q[8], q[9], flag[0];
Q q[0], q[1], q[2], q[3], q[4], q[5], q[6], q[7], q[8], q[9], flag[0];
Q q[0], q[1], q[2], q[3], q[4], q[5], q[6], q[7], q[8], q[9], flag[0];
Q q[0], q[1], q[2], q[3], q[4], q[5], q[6], q[7], q[8], q[9], flag[0];
Q q[0], q[1], q[2], q[3], q[4], q[5], q[6], q[7], q[8], q[9], flag[0];
barrier q[0], q[1], q[2], q[3], q[4], q[5], q[6], q[7], q[8], q[9], flag[0];
meas[0] = measure q[0];
meas[1] = measure q[1];
meas[2] = measure q[2];
meas[3] = measure q[3];
meas[4] = measure q[4];
meas[5] = measure q[5];
meas[6] = measure q[6];
meas[7] = measure q[7];
meas[8] = measure q[8];
meas[9] = measure q[9];
meas[10] = measure flag[0];
