[package]
name = "unique_table"
version = "0.1.0"
edition = "2021"

[lib]
name = "unique_table"
path = "lib.rs"
crate-type = ["cdylib"]

[dependencies]
dashmap = "5.5"
lazy_static = "1.4"
num-complex = "0.4"
libc = "0.2"

[dev-dependencies]
tokio = { version = "1.0", features = ["full"] }

