#include "benchHwb5tc.hpp"

void benchHwb5tc() {
    QMDDState ket_0 = state::Ket0();
    QMDDEdge firstEdge = mathUtils::kron(ket_0.getInitialEdge(), ket_0.getInitialEdge());
    firstEdge = mathUtils::kron(firstEdge, firstEdge);
    firstEdge = mathUtils::kron(firstEdge, ket_0.getInitialEdge());
    QuantumCircuit circuit(5, QMDDState(firstEdge));
    circuit.addCX(3, 1);
    circuit.addCX(4, 3);
    vector<int> controlIndexes = {2, 3};
    circuit.addToff(controlIndexes, 1);
    circuit.addCX(4, 0);
    controlIndexes = {0, 3};
    circuit.addToff(controlIndexes, 4);
    controlIndexes = {0, 1, 3};
    circuit.addToff(controlIndexes, 2);
    controlIndexes = {2, 4};
    circuit.addToff(controlIndexes, 1);
    circuit.addCX(4, 0);
    controlIndexes = {0, 1, 2, 3};
    circuit.addToff(controlIndexes, 4);
    controlIndexes = {0, 3, 4};
    circuit.addToff(controlIndexes, 1);
    controlIndexes = {0, 1, 4};
    circuit.addToff(controlIndexes, 3);
    controlIndexes = {0, 4};
    circuit.addToff(controlIndexes, 2);
    controlIndexes = {1, 4};
    circuit.addToff(controlIndexes, 0);
    controlIndexes = {0, 1, 4};
    circuit.addToff(controlIndexes, 2);
    circuit.addCX(0, 1);
    controlIndexes = {1, 2, 3, 4};
    circuit.addToff(controlIndexes, 0);
    circuit.addCX(1, 2);
    controlIndexes = {2, 3, 4};
    circuit.addToff(controlIndexes, 1);
    circuit.addCX(1, 2);
    circuit.addCX(0, 1);
    controlIndexes = {3, 4};
    circuit.addToff(controlIndexes, 2);
    circuit.addCX(2, 3);
    controlIndexes = {1, 2, 4};
    circuit.addToff(controlIndexes, 3);
    controlIndexes = {1, 2, 4};
    circuit.addToff(controlIndexes, 0);
    controlIndexes = {0, 3, 4};
    circuit.addToff(controlIndexes, 2);
    circuit.addCX(2, 3);
    controlIndexes = {2, 4};
    circuit.addToff(controlIndexes, 1);
    controlIndexes = {3, 4};
    circuit.addToff(controlIndexes, 0);
    circuit.addCX(4, 2);
    controlIndexes = {2, 4};
    circuit.addToff(controlIndexes, 0);
    controlIndexes = {1, 2, 3};
    circuit.addToff(controlIndexes, 4);
    circuit.addCX(4, 2);
    controlIndexes = {2, 3};
    circuit.addToff(controlIndexes, 4);
    controlIndexes = {0, 2, 3};
    circuit.addToff(controlIndexes, 1);
    controlIndexes = {2, 3};
    circuit.addToff(controlIndexes, 1);
    circuit.addCX(4, 3);
    controlIndexes = {1, 3};
    circuit.addToff(controlIndexes, 4);
    circuit.addCX(4, 3);
    circuit.addCX(4, 0);
    circuit.addCX(4, 1);
    controlIndexes = {0, 1, 2};
    circuit.addToff(controlIndexes, 3);
    circuit.addCX(3, 1);
    controlIndexes = {1, 2};
    circuit.addToff(controlIndexes, 0);
    controlIndexes = {0, 2};
    circuit.addToff(controlIndexes, 1);
    circuit.addToff(controlIndexes, 4);
    circuit.addCX(4, 0);
    controlIndexes = {1, 4};
    circuit.addToff(controlIndexes, 2);
    circuit.addCX(2, 3);
    circuit.addCX(3, 2);
    circuit.addCX(1, 2);
    controlIndexes = {0, 1};
    circuit.addToff(controlIndexes, 3);
    controlIndexes = {1, 3};
    circuit.addToff(controlIndexes, 0);
    circuit.addCX(0, 1);
    circuit.addCX(2, 1);
    circuit.addCX(1, 0);
    circuit.simulate();
}