#include "benchHwb5tc.hpp"

void benchHwb5tc() {
    QuantumCircuit circuit(5);
    circuit.addCX(3, 1);
    circuit.addCX(4, 3);
    array<int, 2> controlToff = {2, 3};
    circuit.addToff(controlToff, 1);
    circuit.addCX(4, 0);
    controlToff = {0, 3};
    circuit.addToff(controlToff, 4);
    vector<int> controlMCT = {0, 1, 3};
    circuit.addMCT(controlMCT, 2);
    controlToff = {2, 4};
    circuit.addToff(controlToff, 1);
    circuit.addCX(4, 0);
    controlMCT = {0, 1, 2, 3};
    circuit.addMCT(controlMCT, 4);
    controlMCT = {0, 3, 4};
    circuit.addMCT(controlMCT, 1);
    controlMCT = {0, 1, 4};
    circuit.addMCT(controlMCT, 3);
    controlToff = {0, 4};
    circuit.addToff(controlToff, 2);
    controlToff = {1, 4};
    circuit.addToff(controlToff, 0);
    controlMCT = {0, 1, 4};
    circuit.addMCT(controlMCT, 2);
    circuit.addCX(0, 1);
    controlMCT = {1, 2, 3, 4};
    circuit.addMCT(controlMCT, 0);
    circuit.addCX(1, 2);
    controlMCT = {2, 3, 4};
    circuit.addMCT(controlMCT, 1);
    circuit.addCX(1, 2);
    circuit.addCX(0, 1);
    controlToff = {3, 4};
    circuit.addToff(controlToff, 2);
    circuit.addCX(2, 3);
    controlMCT = {1, 2, 4};
    circuit.addMCT(controlMCT, 3);
    controlMCT = {1, 2, 4};
    circuit.addMCT(controlMCT, 0);
    controlMCT = {0, 3, 4};
    circuit.addMCT(controlMCT, 2);
    circuit.addCX(2, 3);
    controlToff = {2, 4};
    circuit.addToff(controlToff, 1);
    controlToff = {3, 4};
    circuit.addToff(controlToff, 0);
    circuit.addCX(4, 2);
    controlToff = {2, 4};
    circuit.addToff(controlToff, 0);
    controlMCT = {1, 2, 3};
    circuit.addMCT(controlMCT, 4);
    circuit.addCX(4, 2);
    controlToff = {2, 3};
    circuit.addToff(controlToff, 4);
    controlMCT = {0, 2, 3};
    circuit.addMCT(controlMCT, 1);
    controlToff = {2, 3};
    circuit.addToff(controlToff, 1);
    circuit.addCX(4, 3);
    controlToff = {1, 3};
    circuit.addToff(controlToff, 4);
    circuit.addCX(4, 3);
    circuit.addCX(4, 0);
    circuit.addCX(4, 1);
    controlMCT = {0, 1, 2};
    circuit.addMCT(controlMCT, 3);
    circuit.addCX(3, 1);
    controlToff = {1, 2};
    circuit.addToff(controlToff, 0);
    controlToff = {0, 2};
    circuit.addToff(controlToff, 1);
    circuit.addToff(controlToff, 4);
    circuit.addCX(4, 0);
    controlToff = {1, 4};
    circuit.addToff(controlToff, 2);
    circuit.addCX(2, 3);
    circuit.addCX(3, 2);
    circuit.addCX(1, 2);
    controlToff = {0, 1};
    circuit.addToff(controlToff, 3);
    controlToff = {1, 3};
    circuit.addToff(controlToff, 0);
    circuit.addCX(0, 1);
    circuit.addCX(2, 1);
    circuit.addCX(1, 0);
    circuit.simulate();
}