#include "qpeInexact18MQT.hpp"

void qpeInexact18MQT() {
    array<int, 18> c;
    QuantumCircuit qc(18);
    qc.setRegister(0, 17);
    qc.setRegister(1, 1);
    
    qc.addX(qc.quantumRegister_[1][0]);
    qc.addH(qc.quantumRegister_[0][0]);
    qc.addH(qc.quantumRegister_[0][1]);
    qc.addH(qc.quantumRegister_[0][2]);
    qc.addH(qc.quantumRegister_[0][3]);
    qc.addH(qc.quantumRegister_[0][4]);
    qc.addH(qc.quantumRegister_[0][5]);
    qc.addH(qc.quantumRegister_[0][6]);
    qc.addH(qc.quantumRegister_[0][7]);
    qc.addH(qc.quantumRegister_[0][8]);
    qc.addH(qc.quantumRegister_[0][9]);
    qc.addH(qc.quantumRegister_[0][10]);
    qc.addH(qc.quantumRegister_[0][11]);
    qc.addH(qc.quantumRegister_[0][12]);
    qc.addH(qc.quantumRegister_[0][13]);
    qc.addH(qc.quantumRegister_[0][14]);
    qc.addH(qc.quantumRegister_[0][15]);
    qc.addH(qc.quantumRegister_[0][16]);
    qc.addCP(qc.quantumRegister_[1][0], qc.quantumRegister_[0][0], (-2.6929751784826754));
    qc.addCP(qc.quantumRegister_[1][0], qc.quantumRegister_[0][1], (0.8972349502142358));
    qc.addCP(qc.quantumRegister_[1][0], qc.quantumRegister_[0][2], (1.7944699004284717));
    qc.addCP(qc.quantumRegister_[1][0], qc.quantumRegister_[0][3], (-2.694245506322643));
    qc.addCP(qc.quantumRegister_[1][0], qc.quantumRegister_[0][4], (0.8946942945343002));
    qc.addCP(qc.quantumRegister_[1][0], qc.quantumRegister_[0][5], (1.7893885890686003));
    qc.addCP(qc.quantumRegister_[1][0], qc.quantumRegister_[0][6], (-2.7044081290423856));
    qc.addCP(qc.quantumRegister_[1][0], qc.quantumRegister_[0][7], (0.8743690490948155));
    qc.addCP(qc.quantumRegister_[1][0], qc.quantumRegister_[0][8], (1.748738098189631));
    qc.addCP(qc.quantumRegister_[1][0], qc.quantumRegister_[0][9], (-2.7857091108003242));
    qc.addCP(qc.quantumRegister_[1][0], qc.quantumRegister_[0][10], (0.7117670855789375));
    qc.addCP(qc.quantumRegister_[1][0], qc.quantumRegister_[0][11], (1.423534171157875));
    qc.addCP(qc.quantumRegister_[1][0], qc.quantumRegister_[0][12], (2.84706834231575));
    qc.addCP(qc.quantumRegister_[1][0], qc.quantumRegister_[0][13], (-3*M_PI/16));
    qc.addCP(qc.quantumRegister_[1][0], qc.quantumRegister_[0][14], (-3*M_PI/8));
    qc.addCP(qc.quantumRegister_[1][0], qc.quantumRegister_[0][15], (-3*M_PI/4));
    qc.addCP(qc.quantumRegister_[1][0], qc.quantumRegister_[0][16], (M_PI/2));
    qc.addSWAP(qc.quantumRegister_[0][7], qc.quantumRegister_[0][9]);
    qc.addSWAP(qc.quantumRegister_[0][6], qc.quantumRegister_[0][10]);
    qc.addSWAP(qc.quantumRegister_[0][5], qc.quantumRegister_[0][11]);
    qc.addSWAP(qc.quantumRegister_[0][4], qc.quantumRegister_[0][12]);
    qc.addSWAP(qc.quantumRegister_[0][3], qc.quantumRegister_[0][13]);
    qc.addSWAP(qc.quantumRegister_[0][2], qc.quantumRegister_[0][14]);
    qc.addSWAP(qc.quantumRegister_[0][1], qc.quantumRegister_[0][15]);
    qc.addSWAP(qc.quantumRegister_[0][0], qc.quantumRegister_[0][16]);
    qc.addH(qc.quantumRegister_[0][0]);
    qc.addCP(qc.quantumRegister_[0][1], qc.quantumRegister_[0][0], (-M_PI/2));
    qc.addH(qc.quantumRegister_[0][1]);
    qc.addCP(qc.quantumRegister_[0][2], qc.quantumRegister_[0][0], (-M_PI/4));
    qc.addCP(qc.quantumRegister_[0][2], qc.quantumRegister_[0][1], (-M_PI/2));
    qc.addH(qc.quantumRegister_[0][2]);
    qc.addCP(qc.quantumRegister_[0][3], qc.quantumRegister_[0][0], (-M_PI/8));
    qc.addCP(qc.quantumRegister_[0][3], qc.quantumRegister_[0][1], (-M_PI/4));
    qc.addCP(qc.quantumRegister_[0][3], qc.quantumRegister_[0][2], (-M_PI/2));
    qc.addH(qc.quantumRegister_[0][3]);
    qc.addCP(qc.quantumRegister_[0][4], qc.quantumRegister_[0][0], (-M_PI/16));
    qc.addCP(qc.quantumRegister_[0][4], qc.quantumRegister_[0][1], (-M_PI/8));
    qc.addCP(qc.quantumRegister_[0][4], qc.quantumRegister_[0][2], (-M_PI/4));
    qc.addCP(qc.quantumRegister_[0][4], qc.quantumRegister_[0][3], (-M_PI/2));
    qc.addH(qc.quantumRegister_[0][4]);
    qc.addCP(qc.quantumRegister_[0][5], qc.quantumRegister_[0][0], (-M_PI/32));
    qc.addCP(qc.quantumRegister_[0][5], qc.quantumRegister_[0][1], (-M_PI/16));
    qc.addCP(qc.quantumRegister_[0][5], qc.quantumRegister_[0][2], (-M_PI/8));
    qc.addCP(qc.quantumRegister_[0][5], qc.quantumRegister_[0][3], (-M_PI/4));
    qc.addCP(qc.quantumRegister_[0][5], qc.quantumRegister_[0][4], (-M_PI/2));
    qc.addH(qc.quantumRegister_[0][5]);
    qc.addCP(qc.quantumRegister_[0][6], qc.quantumRegister_[0][0], (-M_PI/64));
    qc.addCP(qc.quantumRegister_[0][6], qc.quantumRegister_[0][1], (-M_PI/32));
    qc.addCP(qc.quantumRegister_[0][6], qc.quantumRegister_[0][2], (-M_PI/16));
    qc.addCP(qc.quantumRegister_[0][6], qc.quantumRegister_[0][3], (-M_PI/8));
    qc.addCP(qc.quantumRegister_[0][6], qc.quantumRegister_[0][4], (-M_PI/4));
    qc.addCP(qc.quantumRegister_[0][6], qc.quantumRegister_[0][5], (-M_PI/2));
    qc.addH(qc.quantumRegister_[0][6]);
    qc.addCP(qc.quantumRegister_[0][7], qc.quantumRegister_[0][0], (-M_PI/128));
    qc.addCP(qc.quantumRegister_[0][7], qc.quantumRegister_[0][1], (-M_PI/64));
    qc.addCP(qc.quantumRegister_[0][7], qc.quantumRegister_[0][2], (-M_PI/32));
    qc.addCP(qc.quantumRegister_[0][7], qc.quantumRegister_[0][3], (-M_PI/16));
    qc.addCP(qc.quantumRegister_[0][7], qc.quantumRegister_[0][4], (-M_PI/8));
    qc.addCP(qc.quantumRegister_[0][7], qc.quantumRegister_[0][5], (-M_PI/4));
    qc.addCP(qc.quantumRegister_[0][7], qc.quantumRegister_[0][6], (-M_PI/2));
    qc.addH(qc.quantumRegister_[0][7]);
    qc.addCP(qc.quantumRegister_[0][8], qc.quantumRegister_[0][0], (-M_PI/256));
    qc.addCP(qc.quantumRegister_[0][8], qc.quantumRegister_[0][1], (-M_PI/128));
    qc.addCP(qc.quantumRegister_[0][8], qc.quantumRegister_[0][2], (-M_PI/64));
    qc.addCP(qc.quantumRegister_[0][8], qc.quantumRegister_[0][3], (-M_PI/32));
    qc.addCP(qc.quantumRegister_[0][8], qc.quantumRegister_[0][4], (-M_PI/16));
    qc.addCP(qc.quantumRegister_[0][8], qc.quantumRegister_[0][5], (-M_PI/8));
    qc.addCP(qc.quantumRegister_[0][8], qc.quantumRegister_[0][6], (-M_PI/4));
    qc.addCP(qc.quantumRegister_[0][8], qc.quantumRegister_[0][7], (-M_PI/2));
    qc.addH(qc.quantumRegister_[0][8]);
    qc.addCP(qc.quantumRegister_[0][9], qc.quantumRegister_[0][0], (-M_PI/512));
    qc.addCP(qc.quantumRegister_[0][9], qc.quantumRegister_[0][1], (-M_PI/256));
    qc.addCP(qc.quantumRegister_[0][9], qc.quantumRegister_[0][2], (-M_PI/128));
    qc.addCP(qc.quantumRegister_[0][9], qc.quantumRegister_[0][3], (-M_PI/64));
    qc.addCP(qc.quantumRegister_[0][9], qc.quantumRegister_[0][4], (-M_PI/32));
    qc.addCP(qc.quantumRegister_[0][9], qc.quantumRegister_[0][5], (-M_PI/16));
    qc.addCP(qc.quantumRegister_[0][9], qc.quantumRegister_[0][6], (-M_PI/8));
    qc.addCP(qc.quantumRegister_[0][9], qc.quantumRegister_[0][7], (-M_PI/4));
    qc.addCP(qc.quantumRegister_[0][9], qc.quantumRegister_[0][8], (-M_PI/2));
    qc.addH(qc.quantumRegister_[0][9]);
    qc.addCP(qc.quantumRegister_[0][10], qc.quantumRegister_[0][0], (-M_PI/1024));
    qc.addCP(qc.quantumRegister_[0][10], qc.quantumRegister_[0][1], (-M_PI/512));
    qc.addCP(qc.quantumRegister_[0][10], qc.quantumRegister_[0][2], (-M_PI/256));
    qc.addCP(qc.quantumRegister_[0][10], qc.quantumRegister_[0][3], (-M_PI/128));
    qc.addCP(qc.quantumRegister_[0][10], qc.quantumRegister_[0][4], (-M_PI/64));
    qc.addCP(qc.quantumRegister_[0][10], qc.quantumRegister_[0][5], (-M_PI/32));
    qc.addCP(qc.quantumRegister_[0][10], qc.quantumRegister_[0][6], (-M_PI/16));
    qc.addCP(qc.quantumRegister_[0][10], qc.quantumRegister_[0][7], (-M_PI/8));
    qc.addCP(qc.quantumRegister_[0][10], qc.quantumRegister_[0][8], (-M_PI/4));
    qc.addCP(qc.quantumRegister_[0][10], qc.quantumRegister_[0][9], (-M_PI/2));
    qc.addH(qc.quantumRegister_[0][10]);
    qc.addCP(qc.quantumRegister_[0][11], qc.quantumRegister_[0][0], (-M_PI/2048));
    qc.addCP(qc.quantumRegister_[0][11], qc.quantumRegister_[0][1], (-M_PI/1024));
    qc.addCP(qc.quantumRegister_[0][11], qc.quantumRegister_[0][2], (-M_PI/512));
    qc.addCP(qc.quantumRegister_[0][11], qc.quantumRegister_[0][3], (-M_PI/256));
    qc.addCP(qc.quantumRegister_[0][11], qc.quantumRegister_[0][4], (-M_PI/128));
    qc.addCP(qc.quantumRegister_[0][11], qc.quantumRegister_[0][5], (-M_PI/64));
    qc.addCP(qc.quantumRegister_[0][11], qc.quantumRegister_[0][6], (-M_PI/32));
    qc.addCP(qc.quantumRegister_[0][11], qc.quantumRegister_[0][7], (-M_PI/16));
    qc.addCP(qc.quantumRegister_[0][11], qc.quantumRegister_[0][8], (-M_PI/8));
    qc.addCP(qc.quantumRegister_[0][11], qc.quantumRegister_[0][9], (-M_PI/4));
    qc.addCP(qc.quantumRegister_[0][11], qc.quantumRegister_[0][10], (-M_PI/2));
    qc.addH(qc.quantumRegister_[0][11]);
    qc.addCP(qc.quantumRegister_[0][12], qc.quantumRegister_[0][0], (-M_PI/4096));
    qc.addCP(qc.quantumRegister_[0][12], qc.quantumRegister_[0][1], (-M_PI/2048));
    qc.addCP(qc.quantumRegister_[0][12], qc.quantumRegister_[0][2], (-M_PI/1024));
    qc.addCP(qc.quantumRegister_[0][12], qc.quantumRegister_[0][3], (-M_PI/512));
    qc.addCP(qc.quantumRegister_[0][12], qc.quantumRegister_[0][4], (-M_PI/256));
    qc.addCP(qc.quantumRegister_[0][12], qc.quantumRegister_[0][5], (-M_PI/128));
    qc.addCP(qc.quantumRegister_[0][12], qc.quantumRegister_[0][6], (-M_PI/64));
    qc.addCP(qc.quantumRegister_[0][12], qc.quantumRegister_[0][7], (-M_PI/32));
    qc.addCP(qc.quantumRegister_[0][12], qc.quantumRegister_[0][8], (-M_PI/16));
    qc.addCP(qc.quantumRegister_[0][12], qc.quantumRegister_[0][9], (-M_PI/8));
    qc.addCP(qc.quantumRegister_[0][12], qc.quantumRegister_[0][10], (-M_PI/4));
    qc.addCP(qc.quantumRegister_[0][12], qc.quantumRegister_[0][11], (-M_PI/2));
    qc.addH(qc.quantumRegister_[0][12]);
    qc.addCP(qc.quantumRegister_[0][13], qc.quantumRegister_[0][0], (-M_PI/8192));
    qc.addCP(qc.quantumRegister_[0][13], qc.quantumRegister_[0][1], (-M_PI/4096));
    qc.addCP(qc.quantumRegister_[0][13], qc.quantumRegister_[0][2], (-M_PI/2048));
    qc.addCP(qc.quantumRegister_[0][13], qc.quantumRegister_[0][3], (-M_PI/1024));
    qc.addCP(qc.quantumRegister_[0][13], qc.quantumRegister_[0][4], (-M_PI/512));
    qc.addCP(qc.quantumRegister_[0][13], qc.quantumRegister_[0][5], (-M_PI/256));
    qc.addCP(qc.quantumRegister_[0][13], qc.quantumRegister_[0][6], (-M_PI/128));
    qc.addCP(qc.quantumRegister_[0][13], qc.quantumRegister_[0][7], (-M_PI/64));
    qc.addCP(qc.quantumRegister_[0][13], qc.quantumRegister_[0][8], (-M_PI/32));
    qc.addCP(qc.quantumRegister_[0][13], qc.quantumRegister_[0][9], (-M_PI/16));
    qc.addCP(qc.quantumRegister_[0][13], qc.quantumRegister_[0][10], (-M_PI/8));
    qc.addCP(qc.quantumRegister_[0][13], qc.quantumRegister_[0][11], (-M_PI/4));
    qc.addCP(qc.quantumRegister_[0][13], qc.quantumRegister_[0][12], (-M_PI/2));
    qc.addH(qc.quantumRegister_[0][13]);
    qc.addCP(qc.quantumRegister_[0][14], qc.quantumRegister_[0][0], (-M_PI/16384));
    qc.addCP(qc.quantumRegister_[0][14], qc.quantumRegister_[0][1], (-M_PI/8192));
    qc.addCP(qc.quantumRegister_[0][14], qc.quantumRegister_[0][2], (-M_PI/4096));
    qc.addCP(qc.quantumRegister_[0][14], qc.quantumRegister_[0][3], (-M_PI/2048));
    qc.addCP(qc.quantumRegister_[0][14], qc.quantumRegister_[0][4], (-M_PI/1024));
    qc.addCP(qc.quantumRegister_[0][14], qc.quantumRegister_[0][5], (-M_PI/512));
    qc.addCP(qc.quantumRegister_[0][14], qc.quantumRegister_[0][6], (-M_PI/256));
    qc.addCP(qc.quantumRegister_[0][14], qc.quantumRegister_[0][7], (-M_PI/128));
    qc.addCP(qc.quantumRegister_[0][14], qc.quantumRegister_[0][8], (-M_PI/64));
    qc.addCP(qc.quantumRegister_[0][14], qc.quantumRegister_[0][9], (-M_PI/32));
    qc.addCP(qc.quantumRegister_[0][14], qc.quantumRegister_[0][10], (-M_PI/16));
    qc.addCP(qc.quantumRegister_[0][14], qc.quantumRegister_[0][11], (-M_PI/8));
    qc.addCP(qc.quantumRegister_[0][14], qc.quantumRegister_[0][12], (-M_PI/4));
    qc.addCP(qc.quantumRegister_[0][14], qc.quantumRegister_[0][13], (-M_PI/2));
    qc.addH(qc.quantumRegister_[0][14]);
    qc.addCP(qc.quantumRegister_[0][15], qc.quantumRegister_[0][0], (-M_PI/32768));
    qc.addCP(qc.quantumRegister_[0][15], qc.quantumRegister_[0][1], (-M_PI/16384));
    qc.addCP(qc.quantumRegister_[0][15], qc.quantumRegister_[0][2], (-M_PI/8192));
    qc.addCP(qc.quantumRegister_[0][15], qc.quantumRegister_[0][3], (-M_PI/4096));
    qc.addCP(qc.quantumRegister_[0][15], qc.quantumRegister_[0][4], (-M_PI/2048));
    qc.addCP(qc.quantumRegister_[0][15], qc.quantumRegister_[0][5], (-M_PI/1024));
    qc.addCP(qc.quantumRegister_[0][15], qc.quantumRegister_[0][6], (-M_PI/512));
    qc.addCP(qc.quantumRegister_[0][15], qc.quantumRegister_[0][7], (-M_PI/256));
    qc.addCP(qc.quantumRegister_[0][15], qc.quantumRegister_[0][8], (-M_PI/128));
    qc.addCP(qc.quantumRegister_[0][15], qc.quantumRegister_[0][9], (-M_PI/64));
    qc.addCP(qc.quantumRegister_[0][15], qc.quantumRegister_[0][10], (-M_PI/32));
    qc.addCP(qc.quantumRegister_[0][15], qc.quantumRegister_[0][11], (-M_PI/16));
    qc.addCP(qc.quantumRegister_[0][15], qc.quantumRegister_[0][12], (-M_PI/8));
    qc.addCP(qc.quantumRegister_[0][15], qc.quantumRegister_[0][13], (-M_PI/4));
    qc.addCP(qc.quantumRegister_[0][15], qc.quantumRegister_[0][14], (-M_PI/2));
    qc.addH(qc.quantumRegister_[0][15]);
    qc.addCP(qc.quantumRegister_[0][16], qc.quantumRegister_[0][0], (-M_PI/65536));
    qc.addCP(qc.quantumRegister_[0][16], qc.quantumRegister_[0][1], (-M_PI/32768));
    qc.addCP(qc.quantumRegister_[0][16], qc.quantumRegister_[0][2], (-M_PI/16384));
    qc.addCP(qc.quantumRegister_[0][16], qc.quantumRegister_[0][3], (-M_PI/8192));
    qc.addCP(qc.quantumRegister_[0][16], qc.quantumRegister_[0][4], (-M_PI/4096));
    qc.addCP(qc.quantumRegister_[0][16], qc.quantumRegister_[0][5], (-M_PI/2048));
    qc.addCP(qc.quantumRegister_[0][16], qc.quantumRegister_[0][6], (-M_PI/1024));
    qc.addCP(qc.quantumRegister_[0][16], qc.quantumRegister_[0][7], (-M_PI/512));
    qc.addCP(qc.quantumRegister_[0][16], qc.quantumRegister_[0][8], (-M_PI/256));
    qc.addCP(qc.quantumRegister_[0][16], qc.quantumRegister_[0][9], (-M_PI/128));
    qc.addCP(qc.quantumRegister_[0][16], qc.quantumRegister_[0][10], (-M_PI/64));
    qc.addCP(qc.quantumRegister_[0][16], qc.quantumRegister_[0][11], (-M_PI/32));
    qc.addCP(qc.quantumRegister_[0][16], qc.quantumRegister_[0][12], (-M_PI/16));
    qc.addCP(qc.quantumRegister_[0][16], qc.quantumRegister_[0][13], (-M_PI/8));
    qc.addCP(qc.quantumRegister_[0][16], qc.quantumRegister_[0][14], (-M_PI/4));
    qc.addCP(qc.quantumRegister_[0][16], qc.quantumRegister_[0][15], (-M_PI/2));
    qc.addH(qc.quantumRegister_[0][16]);
    qc.addBarrier();
    c[0] = qc.measure(qc.quantumRegister_[0][0]);
    c[1] = qc.measure(qc.quantumRegister_[0][1]);
    c[2] = qc.measure(qc.quantumRegister_[0][2]);
    c[3] = qc.measure(qc.quantumRegister_[0][3]);
    c[4] = qc.measure(qc.quantumRegister_[0][4]);
    c[5] = qc.measure(qc.quantumRegister_[0][5]);
    c[6] = qc.measure(qc.quantumRegister_[0][6]);
    c[7] = qc.measure(qc.quantumRegister_[0][7]);
    c[8] = qc.measure(qc.quantumRegister_[0][8]);
    c[9] = qc.measure(qc.quantumRegister_[0][9]);
    c[10] = qc.measure(qc.quantumRegister_[0][10]);
    c[11] = qc.measure(qc.quantumRegister_[0][11]);
    c[12] = qc.measure(qc.quantumRegister_[0][12]);
    c[13] = qc.measure(qc.quantumRegister_[0][13]);
    c[14] = qc.measure(qc.quantumRegister_[0][14]);
    c[15] = qc.measure(qc.quantumRegister_[0][15]);
    c[16] = qc.measure(qc.quantumRegister_[0][16]);

    return;
}