/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class OperationCache */

#ifndef _Included_OperationCache
#define _Included_OperationCache
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     OperationCache
 * Method:    nativeInsert
 * Signature: (JDDJ)V
 */
JNIEXPORT void JNICALL Java_OperationCache_nativeInsert
  (JNIEnv *, jclass, jlong, jdouble, jdouble, jlong);

/*
 * Class:     OperationCache
 * Method:    nativeFind
 * Signature: (J)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_OperationCache_nativeFind
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
