/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class OperationCache */

#ifndef _Included_OperationCache
#define _Included_OperationCache
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     OperationCache
 * Method:    putFromCpp
 * Signature: (JDDJ)V
 */
JNIEXPORT void JNICALL Java_OperationCache_putFromCpp
  (JNIEnv *, jclass, jlong, jdouble, jdouble, jlong);

/*
 * Class:     OperationCache
 * Method:    getFromCpp
 * Signature: (J)LOperationResult;
 */
JNIEXPORT jobject JNICALL Java_OperationCache_getFromCpp
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
