#include "bench9symml.hpp"

void bench9symml() {
    QuantumCircuit circuit(10);
    vector<int> controlMCT;

    controlMCT = {8, 7, 6, 5, 4, 3, 2};
    circuit.addMCT(controlMCT, 0);
    controlMCT = {8, 7, 6, 5, 4, 3, 1};
    circuit.addMCT(controlMCT, 0);
    controlMCT = {9, 8, 7, 6, 5, 4, 3};
    circuit.addMCT(controlMCT, 0);
    controlMCT = {8, 7, 6, 4, 2, 1};
    circuit.addMCT(controlMCT, 0);
    controlMCT = {9, 8, 7, 4, 3, 1};
    circuit.addMCT(controlMCT, 0);
    controlMCT = {9, 8, 7, 5, 3, 2};
    circuit.addMCT(controlMCT, 0);
    controlMCT = {9, 7, 6, 3, 2, 1};
    circuit.addMCT(controlMCT, 0);
    circuit.addX(0);
    circuit.addX(3);
    controlMCT = {9, 8, 7, 6, 5, 3, 1};
    circuit.addMCT(controlMCT, 0);
    controlMCT = {9, 7, 6, 5, 4, 3, 2};
    circuit.addMCT(controlMCT, 0);
    circuit.addX(6);
    controlMCT = {9, 8, 6, 5, 4, 3, 2, 1};
    circuit.addMCT(controlMCT, 0);
    circuit.addX(3);
    controlMCT = {7, 6, 5, 4, 3, 2, 1};
    circuit.addMCT(controlMCT, 0);
    circuit.addX(6);
    circuit.addX(7);
    controlMCT = {9, 7, 6, 5, 4, 3, 1};
    circuit.addMCT(controlMCT, 0);
    controlMCT = {9, 8, 7, 6, 4, 3, 2};
    circuit.addMCT(controlMCT, 0);
    controlMCT = {9, 8, 7, 5, 4, 2, 1};
    circuit.addMCT(controlMCT, 0);
    circuit.addX(7);
    circuit.addX(4);
    controlMCT = {8, 6, 5, 4, 3, 2, 1};
    circuit.addMCT(controlMCT, 0);
    circuit.addX(1);
    controlMCT = {9, 8, 7, 6, 5, 4, 3, 2, 1};
    circuit.addMCT(controlMCT, 0);
    controlMCT = {9, 8, 7, 5, 4, 3, 2, 1};
    circuit.addMCT(controlMCT, 0);
    circuit.addX(8);
    controlMCT = {9, 8, 7, 6, 5, 4, 2, 1};
    circuit.addMCT(controlMCT, 0);
    controlMCT = {9, 8, 7, 6, 5, 2, 1};
    circuit.addMCT(controlMCT, 0);
    circuit.addX(7);
    circuit.addX(6);
    circuit.addX(3);
    controlMCT = {9, 8, 7, 6, 5, 4, 3, 2, 1};
    circuit.addMCT(controlMCT, 0);
    controlMCT = {8, 7, 6, 4, 3, 1};
    circuit.addMCT(controlMCT, 0);
    circuit.addX(1);
    circuit.addX(3);
    circuit.addX(6);
    circuit.addX(7);
    circuit.addX(2);
    controlMCT = {9, 8, 7, 6, 5, 4, 2, 1};
    circuit.addMCT(controlMCT, 0);
    controlMCT = {9, 7, 6, 5, 4, 2, 1};
    circuit.addMCT(controlMCT, 0);
    circuit.addX(4);
    controlMCT = {9, 8, 6, 5, 4, 3, 2, 1};
    circuit.addMCT(controlMCT, 0);
    circuit.addX(8);
    circuit.addX(2);
    circuit.addX(9);
    controlMCT = {9, 8, 7, 6, 5, 3, 2, 1};
    circuit.addMCT(controlMCT, 0);
    controlMCT = {9, 8, 6, 5, 3, 2, 1};
    circuit.addMCT(controlMCT, 0);
    circuit.addX(8);
    controlMCT = {9, 8, 7, 5, 4, 3, 2, 1};
    circuit.addMCT(controlMCT, 0);
    circuit.addX(3);
    circuit.addX(7);
    circuit.addX(4);
    circuit.addX(2);
    controlMCT = {9, 8, 7, 6, 5, 4, 3, 2};
    circuit.addMCT(controlMCT, 0);
    controlMCT = {9, 8, 7, 4, 3, 2};
    circuit.addMCT(controlMCT, 0);
    circuit.addX(1);
    controlMCT = {9, 8, 7, 5, 4, 3, 2, 1};
    circuit.addMCT(controlMCT, 0);
    circuit.addX(4);
    circuit.addX(6);
    controlMCT = {9, 8, 7, 6, 5, 4, 3, 2, 1};
    circuit.addMCT(controlMCT, 0);
    controlMCT = {9, 7, 6, 5, 4, 3, 2, 1};
    circuit.addMCT(controlMCT, 0);
    controlMCT = {9, 7, 6, 3, 2, 1};
    circuit.addMCT(controlMCT, 0);
    circuit.addX(3);
    circuit.addX(7);
    circuit.addX(4);
    controlMCT = {9, 8, 7, 6, 5, 4, 3, 2, 1};
    circuit.addMCT(controlMCT, 0);
    controlMCT = {9, 8, 6, 4, 2, 1};
    circuit.addMCT(controlMCT, 0);
    circuit.addX(2);
    circuit.addX(4);
    circuit.addX(8);
    circuit.addX(9);
    circuit.addX(5);
    controlMCT = {9, 8, 6, 5, 4, 3, 2, 1};
    circuit.addMCT(controlMCT, 0);
    controlMCT = {9, 8, 5, 4, 3, 2, 1};
    circuit.addMCT(controlMCT, 0);
    circuit.addX(2);
    controlMCT = {9, 8, 7, 6, 5, 4, 3, 2, 1};
    circuit.addMCT(controlMCT, 0);
    controlMCT = {9, 8, 7, 6, 5, 4, 3, 2};
    circuit.addMCT(controlMCT, 0);
    circuit.addX(8);
    circuit.addX(3);
    controlMCT = {8, 7, 6, 5, 4, 3, 2, 1};
    circuit.addMCT(controlMCT, 0);
    controlMCT = {9, 8, 6, 5, 3, 2, 1};
    circuit.addMCT(controlMCT, 0);
    circuit.addX(1);
    circuit.addX(2);
    circuit.addX(3);
    circuit.addX(6);
    controlMCT = {9, 8, 7, 6, 5, 4, 3, 2, 1};
    circuit.addMCT(controlMCT, 0);
    controlMCT = {9, 8, 7, 6, 5, 3, 2, 1};
    circuit.addMCT(controlMCT, 0);
    circuit.addX(8);
    circuit.addX(9);
    circuit.addX(3);
    controlMCT = {9, 8, 7, 6, 5, 4, 3, 2, 1};
    circuit.addMCT(controlMCT, 0);
    circuit.addX(6);
    circuit.addX(4);
    circuit.addX(2);
    controlMCT = {9, 8, 7, 6, 5, 4, 3, 2, 1};
    circuit.addMCT(controlMCT, 0);
    controlMCT = {9, 6, 5, 4, 3, 2};
    circuit.addMCT(controlMCT, 0);
    circuit.addX(2);
    circuit.addX(8);
    circuit.addX(1);
    controlMCT = {9, 8, 7, 5, 4, 3, 1};
    circuit.addMCT(controlMCT, 0);
    controlMCT = {9, 8, 6, 5, 4, 3, 2, 1};
    circuit.addMCT(controlMCT, 0);
    controlMCT = {9, 8, 5, 4, 3, 2, 1};
    circuit.addMCT(controlMCT, 0);
    circuit.addX(7);
    circuit.addX(2);
    controlMCT = {9, 8, 7, 6, 5, 4, 2};
    circuit.addMCT(controlMCT, 0);
    controlMCT = {8, 7, 6, 5, 4, 3, 2};
    circuit.addMCT(controlMCT, 0);
    circuit.addX(3);
    controlMCT = {8, 7, 6, 5, 4, 3, 2, 1};
    circuit.addMCT(controlMCT, 0);
    circuit.addX(2);
    controlMCT = {9, 8, 7, 6, 5, 4, 2, 1};
    circuit.addMCT(controlMCT, 0);
    controlMCT = {9, 7, 6, 5, 4, 2, 1};
    circuit.addMCT(controlMCT, 0);
    controlMCT = {9, 7, 6, 5, 4, 3, 1};
    circuit.addMCT(controlMCT, 0);
    circuit.addX(6);
    circuit.addX(2);
    controlMCT = {9, 8, 7, 6, 5, 4, 2, 1};
    circuit.addMCT(controlMCT, 0);
    controlMCT = {9, 8, 7, 6, 5, 2, 1};
    circuit.addMCT(controlMCT, 0);
    controlMCT = {9, 8, 7, 5, 3, 2, 1};
    circuit.addMCT(controlMCT, 0);
    circuit.addX(3);
    controlMCT = {9, 7, 6, 5, 4, 3, 2, 1};
    circuit.addMCT(controlMCT, 0);
    controlMCT = {7, 6, 5, 4, 3, 2, 1};
    circuit.addMCT(controlMCT, 0);
    controlMCT = {8, 7, 5, 4, 3, 2, 1};
    circuit.addMCT(controlMCT, 0);
    controlMCT = {7, 5, 4, 3, 2, 1};
    circuit.addMCT(controlMCT, 0);
    circuit.addX(1);
    circuit.addX(2);
    circuit.addX(4);
    circuit.addX(6);
    controlMCT = {9, 8, 7, 6, 5, 4, 3, 2};
    circuit.addMCT(controlMCT, 0);
    controlMCT = {9, 8, 7, 6, 5, 3, 1};
    circuit.addMCT(controlMCT, 0);

    circuit.simulate();
}
