#include "errorCorrectiond3N5.hpp"

void errorCorrectiond3N5() {
    QuantumCircuit q(5);
    vector<int> c(5);
    q.addH(0);
    q.addH(1);
    q.addI(2);
    q.addH(3);
    q.addH(4);
    q.addCX(1, 2);
    q.addH(1);
    q.addH(2);
    q.addCX(1, 2);
    q.addH(1);
    q.addH(2);
    q.addCX(1, 2);
    q.addCX(4, 2);
    q.addCX(1, 2);
    q.addH(1);
    q.addH(2);
    q.addCX(1, 2);
    q.addH(1);
    q.addH(2);
    q.addCX(1, 2);
    q.addSdg(4);
    q.addCX(4, 2);
    q.addH(2);
    q.addCX(4, 2);
    q.addH(2);
    q.addCX(0, 2);
    q.addH(0);
    q.addH(2);
    q.addCX(0, 2);
    q.addH(0);
    q.addH(2);
    q.addCX(0, 2);
    q.addCX(3, 2);
    q.addCX(0, 2);
    q.addH(0);
    q.addH(2);
    q.addCX(0, 2);
    q.addH(0);
    q.addH(2);
    q.addCX(0, 2);
    q.addCX(1, 2);
    q.addH(1);
    q.addH(2);
    q.addCX(1, 2);
    q.addH(1);
    q.addH(2);
    q.addCX(1, 2);
    q.addCX(3, 2);
    q.addCX(1, 2);
    q.addH(1);
    q.addH(2);
    q.addCX(1, 2);
    q.addH(1);
    q.addH(2);
    q.addCX(1, 2);
    q.addCX(3, 2);
    q.addCX(0, 2);
    q.addH(3);
    q.addH(4);
    q.addCX(3, 2);
    q.addH(2);
    q.addH(3);
    q.addCX(3, 2);
    q.addH(2);
    q.addH(3);
    q.addCX(3, 2);
    q.addCX(0, 2);
    q.addCX(3, 2);
    q.addH(2);
    q.addH(3);
    q.addCX(3, 2);
    q.addH(2);
    q.addH(3);
    q.addCX(3, 2);
    q.addCX(4, 2);
    q.addH(2);
    q.addH(4);
    q.addCX(4, 2);
    q.addH(2);
    q.addH(4);
    q.addCX(4, 2);
    q.addCX(0, 2);
    q.addCX(4, 2);
    q.addH(2);
    q.addH(4);
    q.addCX(4, 2);
    q.addH(2);
    q.addH(4);
    q.addCX(4, 2);
    q.addCX(1, 2);
    q.addH(2);
    q.addCX(1, 2);
    q.addH(1);
    q.addCX(4, 2);
    q.addCX(0, 1);
    q.addH(2);
    q.addH(4);
    q.addH(1);
    q.addCX(4, 2);
    q.addH(2);
    q.addH(4);
    q.addCX(4, 2);
    q.addCX(1, 2);
    q.addCX(4, 2);
    q.addH(2);
    q.addH(4);
    q.addCX(4, 2);
    q.addH(2);
    q.addH(4);
    q.addCX(4, 2);
    q.addSdg(1);
    q.addH(2);
    q.addH(3);
    q.addH(4);
    c[0] = q.measure(0);
    c[1] = q.measure(1);
    c[2] = q.measure(2);
    c[3] = q.measure(3);
    c[4] = q.measure(4);
    return;
}
